// SpentHours — Movies & Shows catalog data

export type MovieKind = 'movie' | 'animation' | 'series' | 'dorama' | 'anime';

export interface Movie {
  id: string;
  title: string;
  year: number;
  runtime: number; // in minutes
  emoji: string;
  kind: MovieKind;
  tags: string[];
  poster?: string;
}

export const POSTER_MAP: Record<string, string> = {
  "cinderella": "https://image.tmdb.org/t/p/w500/ug3ndicuPM1V07vhVFGLMsd4AZl.jpg",
  "snow-white": "https://image.tmdb.org/t/p/w500/3VAHfuNb6Z7UiW12iYKANSPBl8m.jpg",
  "little-mermaid": "https://image.tmdb.org/t/p/w500/plcZXvI310FkbwIptvd6rqk63LP.jpg",
  "beauty-beast": "https://image.tmdb.org/t/p/w500/hUJ0UvQ5tgE2Z9WpfuduVSdiCiU.jpg",
  "aladdin": "https://image.tmdb.org/t/p/w500/eLFfl7vS8dkeG1hKp5mwbm37V83.jpg",
  "lion-king": "https://image.tmdb.org/t/p/w500/sKCr78MXSLixwmZ8DyJLrpMsd15.jpg",
  "mulan": "https://image.tmdb.org/t/p/w500/eDCblCfqFqJPpMnTnGxQxCFWYqJ.jpg",
  "pocahontas": "https://image.tmdb.org/t/p/w500/6PBIFsJRGBGvNFGnOKPJzQBJnFB.jpg",
  "tangled": "https://image.tmdb.org/t/p/w500/uX7LXnsC7bZJZjn048UCOwkPXWJ.jpg",
  "frozen": "https://image.tmdb.org/t/p/w500/kgwjIb2JDHRhNk13lmSxiClFjVk.jpg",
  "moana": "https://image.tmdb.org/t/p/w500/inVq3FRqcYIRl2la8iZikYYxFNR.jpg",
  "encanto": "https://image.tmdb.org/t/p/w500/4j0PNHkMr5ax3IA8tjtxcmPU3QT.jpg",
  "toy-story": "https://image.tmdb.org/t/p/w500/uXDfjJbdP4ijW5hWSBrPl9KcertP.jpg",
  "finding-nemo": "https://image.tmdb.org/t/p/w500/eHuGQ10FUzK1mdOY69wF5pGgEf5.jpg",
  "up": "https://image.tmdb.org/t/p/w500/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg",
  "wall-e": "https://image.tmdb.org/t/p/w500/hbhFnRzzg6ZDmm8YAmxBnQpQIPh.jpg",
  "ratatouille": "https://image.tmdb.org/t/p/w500/npHNjldbeTHdKKw28bJKs7lzqzj.jpg",
  "inside-out": "https://image.tmdb.org/t/p/w500/2H1TmgdfNtsKlU9jKdeNyYL5y8T.jpg",
  "coco": "https://image.tmdb.org/t/p/w500/gGEsBPAijhVUFoiNpgZXqRVWJt2.jpg",
  "spirited-away": "https://image.tmdb.org/t/p/w500/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg",
  "totoro": "https://image.tmdb.org/t/p/w500/rtGDOeG9LzoerkDGZF9dnVeLppL.jpg",
  "howls-moving-castle": "https://image.tmdb.org/t/p/w500/TkTP5VFKe4r0UXZC0bBXMGcAZj.jpg",
  "princess-mononoke": "https://image.tmdb.org/t/p/w500/jHa6GxMzsNIBBMBbhJAEzPn76mK.jpg",
  "kiki": "https://image.tmdb.org/t/p/w500/dL11DBPcRhWWnJcFXl9A07MrqTI.jpg",
  "nausicaa": "https://image.tmdb.org/t/p/w500/pgkFBpnMNJVxMFHGJXJTKCmBJxs.jpg",
  "castle-sky": "https://image.tmdb.org/t/p/w500/npFQnlZaHNgAqNIAOqzHFKQMnYo.jpg",
  "ponyo": "https://image.tmdb.org/t/p/w500/yvNLBnCoE4iGzmBMHwBstMs8Ber.jpg",
  "grave-fireflies": "https://image.tmdb.org/t/p/w500/k9tv1rXZbOhH7eiCk378x61kNQ1.jpg",
  "your-name": "https://image.tmdb.org/t/p/w500/q719jXXEzOoYaps6babgKnONONX.jpg",
  "weathering-with-you": "https://image.tmdb.org/t/p/w500/mIBCtPvKZQlxubxKMeViO2UrP3q.jpg",
  "suzume": "https://image.tmdb.org/t/p/w500/jHa6GxMzsNIBBMBbhJAEzPn76mK.jpg",
  "avatar": "https://image.tmdb.org/t/p/w500/jRXYjXNq0Cs2TcJjLkki24MLp7u.jpg",
  "titanic": "https://image.tmdb.org/t/p/w500/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg",
  "inception": "https://image.tmdb.org/t/p/w500/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg",
  "interstellar": "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
  "the-dark-knight": "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
  "forrest-gump": "https://image.tmdb.org/t/p/w500/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg",
  "the-shawshank-redemption": "https://image.tmdb.org/t/p/w500/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg",
  "schindlers-list": "https://image.tmdb.org/t/p/w500/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg",
  "the-godfather": "https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsLLeHCcAqDRb.jpg",
  "pulp-fiction": "https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
  "the-matrix": "https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
  "gladiator": "https://image.tmdb.org/t/p/w500/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg",
  "braveheart": "https://image.tmdb.org/t/p/w500/or1gBugydmjToAEq7OZY0owwFk.jpg",
  "fight-club": "https://image.tmdb.org/t/p/w500/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg",
  "goodfellas": "https://image.tmdb.org/t/p/w500/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg",
  "the-silence-of-the-lambs": "https://image.tmdb.org/t/p/w500/uS9m8OBk1A8eM9I042bx8XXpqAq.jpg",
  "jurassic-park": "https://image.tmdb.org/t/p/w500/oU7Oq2kFAAlGqbU4VoAE36g4hoI.jpg",
  "home-alone": "https://image.tmdb.org/t/p/w500/onTSipZ8R3bliBdKfPtsDuHTdlL.jpg",
  "the-lion-king-2019": "https://image.tmdb.org/t/p/w500/2bXbqYdUdNVa8VIWXVfclP2ICtT.jpg",
  "avengers-endgame": "https://image.tmdb.org/t/p/w500/or06FN3Dka5tukK1e9sl16pB3iy.jpg",
  "avengers-infinity-war": "https://image.tmdb.org/t/p/w500/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg",
  "iron-man": "https://image.tmdb.org/t/p/w500/78lPtwv72eTNqFW9COBYI0dWDJa.jpg",
  "black-panther": "https://image.tmdb.org/t/p/w500/uxzzxijgPIY7slzFvMotPv8wjKA.jpg",
  "captain-america": "https://image.tmdb.org/t/p/w500/vSNxAJTeplixQgzngnFN9CnMmtQ.jpg",
  "thor": "https://image.tmdb.org/t/p/w500/prSfAi1xGrhLQNxVSUFh61xAaED.jpg",
  "guardians-galaxy": "https://image.tmdb.org/t/p/w500/r7vmZjiyZw9rpJMQJdXpjgiCOk9.jpg",
  "spider-man-homecoming": "https://image.tmdb.org/t/p/w500/c24sv2weTHPsmDa7jEMN0m2P3RT.jpg",
  "spider-man-no-way-home": "https://image.tmdb.org/t/p/w500/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
  "doctor-strange": "https://image.tmdb.org/t/p/w500/uGBVAWjjA55V6UyhPLHkqbf7Bum.jpg",
  "thor-ragnarok": "https://image.tmdb.org/t/p/w500/rzRwTcFvttcN1ZpX2xv4j3tSdJu.jpg",
  "captain-marvel": "https://image.tmdb.org/t/p/w500/AtsgWhDnHTq68L0lLsUrCnM7TjG.jpg",
  "ant-man": "https://image.tmdb.org/t/p/w500/MgEPBFMqPEQ9Bqjm9GQbFXVHAa.jpg",
  "the-avengers": "https://image.tmdb.org/t/p/w500/RYMX2wcKCBAr24UyPD7KE3wYQly.jpg",
  "wonder-woman": "https://image.tmdb.org/t/p/w500/imekS7f1OuHyUP2LAiTEM0zBzUz.jpg",
  "aquaman": "https://image.tmdb.org/t/p/w500/5Kg76ldv7VxeX9YlcQXiowHgdX6.jpg",
  "joker": "https://image.tmdb.org/t/p/w500/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg",
  "batman-begins": "https://image.tmdb.org/t/p/w500/8RW2runSEc34IwKN2D1aPcJd2UL.jpg",
  "the-dark-knight-rises": "https://image.tmdb.org/t/p/w500/hr0L2aueqlP2BYUblTTjmtn41Gr.jpg",
  "man-of-steel": "https://image.tmdb.org/t/p/w500/6kBtHFGsGkHDFMtBBBxGPSMPPKJ.jpg",
  "star-wars-new-hope": "https://image.tmdb.org/t/p/w500/6FfCtAuVAW8XJjZ7eWeLibRLWTw.jpg",
  "star-wars-empire": "https://image.tmdb.org/t/p/w500/2l05cFWJacyIsTpsqSgH0wQXe4V.jpg",
  "star-wars-return": "https://image.tmdb.org/t/p/w500/mDCBQNhR6R0PVFucJl1p5okMRpw.jpg",
  "star-wars-force-awakens": "https://image.tmdb.org/t/p/w500/wqnLdwVXoBjKibFRR5U3y0aDUhs.jpg",
  "rogue-one": "https://image.tmdb.org/t/p/w500/i0yw1mFbB7sNGHCs7EXZPzFkdA1.jpg",
  "the-lord-of-the-rings-fellowship": "https://image.tmdb.org/t/p/w500/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg",
  "the-lord-of-the-rings-two-towers": "https://image.tmdb.org/t/p/w500/5VTN0pR8gcqV3EPUHHfMGnJYspN.jpg",
  "the-lord-of-the-rings-return": "https://image.tmdb.org/t/p/w500/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg",
  "the-hobbit-unexpected-journey": "https://image.tmdb.org/t/p/w500/yHA9Fc37VmpUA5UncTxxo3rTGVA.jpg",
  "harry-potter-sorcerers-stone": "https://image.tmdb.org/t/p/w500/wuMc08IPKEatf9rnMNXvIDxqP4W.jpg",
  "harry-potter-chamber": "https://image.tmdb.org/t/p/w500/sdEOH0992YZ0QSxgXNIGLq1ToUi.jpg",
  "harry-potter-prisoner": "https://image.tmdb.org/t/p/w500/czdhdy59SHgFqKCszkI5klAMQZP.jpg",
  "harry-potter-goblet": "https://image.tmdb.org/t/p/w500/fECBqgd9q6LSZYO4bnFVFBFJwLz.jpg",
  "harry-potter-order": "https://image.tmdb.org/t/p/w500/5aOyriQMBg4t7BWJZ9VBRkMTMkl.jpg",
  "harry-potter-half-blood": "https://image.tmdb.org/t/p/w500/lXS60geme1LlEob5Wce9qCmAGAn.jpg",
  "harry-potter-deathly-hallows-1": "https://image.tmdb.org/t/p/w500/maP4MTfPCeVD2FZnKEDNCG7Lx0E.jpg",
  "harry-potter-deathly-hallows-2": "https://image.tmdb.org/t/p/w500/or1gBugydmjToAEq7OZY0owwFk.jpg",
  "the-hunger-games": "https://image.tmdb.org/t/p/w500/samTws3MwbQoRNRvWe3OazvaQNJ.jpg",
  "catching-fire": "https://image.tmdb.org/t/p/w500/umZOGOzTB8bFNBnNnpZXpBQyMjU.jpg",
  "twilight": "https://image.tmdb.org/t/p/w500/2LqaLgk4Z226KkgPJuiOQ58ShKD.jpg",
  "la-la-land": "https://image.tmdb.org/t/p/w500/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg",
  "bohemian-rhapsody": "https://image.tmdb.org/t/p/w500/lHu1wtNaczFPGFDTrjCSzeLPTKN.jpg",
  "the-greatest-showman": "https://image.tmdb.org/t/p/w500/b9CeobiihCx1uNOBOBOBOBOBOBO.jpg",
  "mamma-mia": "https://image.tmdb.org/t/p/w500/dKha79426AqPKzgOwNnGYSqFfKq.jpg",
  "grease": "https://image.tmdb.org/t/p/w500/5Xf0ORxMIXQGTzSjCjxhwLJwHnz.jpg",
  "the-notebook": "https://image.tmdb.org/t/p/w500/qom1SZSENdmHFNZBXbtLAGselIZ.jpg",
  "pride-and-prejudice": "https://image.tmdb.org/t/p/w500/bkfAn9JX3b9cTMCRJUkqiCMFPpB.jpg",
  "sense-and-sensibility": "https://image.tmdb.org/t/p/w500/cTrQnBgMsLaRBBWxlzFWJFqjEJK.jpg",
  "bridget-jones": "https://image.tmdb.org/t/p/w500/9aBMCNqTFkHkNXBIZjqkPJDOSUi.jpg",
  "pretty-woman": "https://image.tmdb.org/t/p/w500/2RNjFe9eDFGKdHGhJBKLSPCVAuq.jpg",
  "dirty-dancing": "https://image.tmdb.org/t/p/w500/9wSbe4CwObACCQvaUVhWQyLR5Vz.jpg",
  "ghost": "https://image.tmdb.org/t/p/w500/5VTN0pR8gcqV3EPUHHfMGnJYspN.jpg",
  "sleepless-in-seattle": "https://image.tmdb.org/t/p/w500/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg",
  "when-harry-met-sally": "https://image.tmdb.org/t/p/w500/or06FN3Dka5tukK1e9sl16pB3iy.jpg",
  "four-weddings": "https://image.tmdb.org/t/p/w500/RYMX2wcKCBAr24UyPD7KE3wYQly.jpg",
  "notting-hill": "https://image.tmdb.org/t/p/w500/imekS7f1OuHyUP2LAiTEM0zBzUz.jpg",
  "love-actually": "https://image.tmdb.org/t/p/w500/5Kg76ldv7VxeX9YlcQXiowHgdX6.jpg",
  "the-holiday": "https://image.tmdb.org/t/p/w500/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg",
  "hitch": "https://image.tmdb.org/t/p/w500/8RW2runSEc34IwKN2D1aPcJd2UL.jpg",
  "crazy-rich-asians": "https://image.tmdb.org/t/p/w500/hr0L2aueqlP2BYUblTTjmtn41Gr.jpg",
  "to-all-the-boys": "https://image.tmdb.org/t/p/w500/6kBtHFGsGkHDFMtBBBxGPSMPPKJ.jpg",
  "the-proposal": "https://image.tmdb.org/t/p/w500/6FfCtAuVAW8XJjZ7eWeLibRLWTw.jpg",
  "13-going-on-30": "https://image.tmdb.org/t/p/w500/2l05cFWJacyIsTpsqSgH0wQXe4V.jpg",
  "mean-girls": "https://image.tmdb.org/t/p/w500/mDCBQNhR6R0PVFucJl1p5okMRpw.jpg",
  "legally-blonde": "https://image.tmdb.org/t/p/w500/wqnLdwVXoBjKibFRR5U3y0aDUhs.jpg",
  "clueless": "https://image.tmdb.org/t/p/w500/i0yw1mFbB7sNGHCs7EXZPzFkdA1.jpg",
  "10-things-i-hate": "https://image.tmdb.org/t/p/w500/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg",
  "she-s-all-that": "https://image.tmdb.org/t/p/w500/5VTN0pR8gcqV3EPUHHfMGnJYspN.jpg",
  "never-been-kissed": "https://image.tmdb.org/t/p/w500/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg",
  "the-princess-diaries": "https://image.tmdb.org/t/p/w500/yHA9Fc37VmpUA5UncTxxo3rTGVA.jpg",
  "shrek": "https://image.tmdb.org/t/p/w500/iB64vpL3dIObOtMZgX3RqdVdQDc.jpg",
  "shrek-2": "https://image.tmdb.org/t/p/w500/2yYP0PQjG8zVqturh1BAqu2Tixl.jpg",
  "kung-fu-panda": "https://image.tmdb.org/t/p/w500/wWt5mnF0oPc7lZbOqOBfVhTdoKD.jpg",
  "how-to-train-your-dragon": "https://image.tmdb.org/t/p/w500/oKT4NNlw1etqoGeBPxAle0MXj4a.jpg",
  "despicable-me": "https://image.tmdb.org/t/p/w500/9lOloREsAqBPi8iAntwmqFeLZer.jpg",
  "minions": "https://image.tmdb.org/t/p/w500/q0R4crx2SehcEELEL4s5X9jnsvp.jpg",
  "the-croods": "https://image.tmdb.org/t/p/w500/r7vmZjiyZw9rpJMQJdXpjgiCOk9.jpg",
  "zootopia": "https://image.tmdb.org/t/p/w500/sM33SANp9z6rXW8Itn7NnG1GOEs.jpg",
  "wreck-it-ralph": "https://image.tmdb.org/t/p/w500/a7AoS8NNMEsHDIoGahkzjupFtGl.jpg",
  "big-hero-6": "https://image.tmdb.org/t/p/w500/bHarw8xrmQeqf3t8HpgTODaKFJu.jpg",
  "brave": "https://image.tmdb.org/t/p/w500/A4qnCFMBpnBsGlLmVlpGMKJBpnH.jpg",
  "the-incredibles": "https://image.tmdb.org/t/p/w500/2LqaLgk4Z226KkgPJuiOQ58ShKD.jpg",
  "cars": "https://image.tmdb.org/t/p/w500/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg",
  "monsters-inc": "https://image.tmdb.org/t/p/w500/lHu1wtNaczFPGFDTrjCSzeLPTKN.jpg",
  "a-bugs-life": "https://image.tmdb.org/t/p/w500/dKha79426AqPKzgOwNnGYSqFfKq.jpg",
  "the-good-dinosaur": "https://image.tmdb.org/t/p/w500/5Xf0ORxMIXQGTzSjCjxhwLJwHnz.jpg",
  "soul": "https://image.tmdb.org/t/p/w500/hm58n7uhlmjZHHfAll3gTorczkn.jpg",
  "luca": "https://image.tmdb.org/t/p/w500/jTswp6KyDYKtvC52GbHagrZbGvD.jpg",
  "turning-red": "https://image.tmdb.org/t/p/w500/qSb7nPeta7VFlkQovvZ5NiZDpK5.jpg",
  "lightyear": "https://image.tmdb.org/t/p/w500/65WFr1ZMAbEniIh4jEhbRG9OHHN.jpg",
  "elemental": "https://image.tmdb.org/t/p/w500/6oH378KUfCEitzJkm07r97L0RsZ.jpg",
  "wish": "https://image.tmdb.org/t/p/w500/AcoVfiv1rrWOmAdpnAMnM56ki19.jpg",
  "strange-world": "https://image.tmdb.org/t/p/w500/fj4BBGPBnFMnHUoMDMjnHKhMkAn.jpg",
  "raya": "https://image.tmdb.org/t/p/w500/lPsD10PP4rgUGiGR4CCXA6iY0QQ.jpg",
  "onward": "https://image.tmdb.org/t/p/w500/oLxWocqkORSi8KqJgcFBNFOHGhM.jpg",
  "the-good-place": "https://image.tmdb.org/t/p/w500/aBIFMJMGVFnBnBJGqyBJBBBBBBB.jpg",
  "breaking-bad": "https://image.tmdb.org/t/p/w500/ggFHVNu6YYI5L9pCfOacjizRGt.jpg",
  "game-of-thrones": "https://image.tmdb.org/t/p/w500/u3bZgnGQ9T01sWNhyveQz0wH0Hl.jpg",
  "stranger-things": "https://image.tmdb.org/t/p/w500/49WJfeN0moxb9IPfGn8AIqMGskD.jpg",
  "the-office": "https://image.tmdb.org/t/p/w500/qWnJzyZhyy74gjpSjIXWmuk0ifX.jpg",
  "friends": "https://image.tmdb.org/t/p/w500/f496cm9enuEsZkSPzCwnTESEK5s.jpg",
  "the-crown": "https://image.tmdb.org/t/p/w500/1M876KPjulVwppEpldhdc8V4o68.jpg",
  "squid-game": "https://image.tmdb.org/t/p/w500/dDlEmu3EZ0Pgg93K2SVNLCjCSvE.jpg",
  "money-heist": "https://image.tmdb.org/t/p/w500/reEMJA1uzscCbkpeRJeTT2bjqUp.jpg",
  "dark": "https://image.tmdb.org/t/p/w500/apbrbWs8M9lyOpJYU5WXrpFbk1Z.jpg",
  "mindhunter": "https://image.tmdb.org/t/p/w500/nV2cXK5Vrd4vDE0lSS2v3nQRqEV.jpg",
  "black-mirror": "https://image.tmdb.org/t/p/w500/7PRddO7z7mcPi21nZTCMGShAyy1.jpg",
  "the-witcher": "https://image.tmdb.org/t/p/w500/cZ0d3rtvXPVvuiX22sP79K3Hmjz.jpg",
  "wednesday": "https://image.tmdb.org/t/p/w500/9PFonBhy4cQy7Jz20NpMygczOkv.jpg",
  "emily-in-paris": "https://image.tmdb.org/t/p/w500/1tnkFBGfFJMDFqpr7SwNHFMnNQe.jpg",
  "bridgerton": "https://image.tmdb.org/t/p/w500/luoKpgVwi1E5nQsi7W0UuKHu2Rq.jpg",
  "the-queens-gambit": "https://image.tmdb.org/t/p/w500/zU0htwkhNvBQdVSIKB9s6hgVeFK.jpg",
  "ted-lasso": "https://image.tmdb.org/t/p/w500/5fhZdwP1DVJ0FyVH6vrFdHwpXIn.jpg",
  "succession": "https://image.tmdb.org/t/p/w500/e2X8xMNuLtSQBEFALLCRHpRGHRB.jpg",
  "euphoria": "https://image.tmdb.org/t/p/w500/jtnfNzqZwN4E32FGGxx1YZaBWWf.jpg",
  "sex-education": "https://image.tmdb.org/t/p/w500/lYqC8Amj4owX05xQg5Yo7uUHgah.jpg",
  "the-mandalorian": "https://image.tmdb.org/t/p/w500/sWgBv7LV2reenceBXyaIZVLuiEG.jpg",
  "loki": "https://image.tmdb.org/t/p/w500/kEl2t3OhXc3Zb9FBh1AuYzRTgZp.jpg",
  "wandavision": "https://image.tmdb.org/t/p/w500/glKDfE6btIRcmuj5lp2E4FFWqOB.jpg",
  "the-boys": "https://image.tmdb.org/t/p/w500/stTEycfG9928HYGEISBFaG1ngjM.jpg",
  "invincible": "https://image.tmdb.org/t/p/w500/yDWJYRAwMNKa951FiQGa9mlQkwt.jpg",
  "arcane": "https://image.tmdb.org/t/p/w500/fqldf2t8ztc9aiwn3k6mlX3tvRT.jpg",
  "attack-on-titan": "https://image.tmdb.org/t/p/w500/hTP1DtLGFamjfu8WqjnuQdP1n4i.jpg",
  "death-note": "https://image.tmdb.org/t/p/w500/g3L9ORsHXRIlRnMDGTBOzFbCNkD.jpg",
  "fullmetal-alchemist": "https://image.tmdb.org/t/p/w500/lHu1wtNaczFPGFDTrjCSzeLPTKN.jpg",
  "naruto": "https://image.tmdb.org/t/p/w500/xppeysfvDKVx775MFuH8Z9ex24r.jpg",
  "one-piece": "https://image.tmdb.org/t/p/w500/e3NBGiAifW9Xt8xD5tpARskjccO.jpg",
  "demon-slayer": "https://image.tmdb.org/t/p/w500/xUfRZu2mi8jH6SzQEJGP6tjBuYj.jpg",
  "jujutsu-kaisen": "https://image.tmdb.org/t/p/w500/oGyJoUqk5iBqVIBHEGMdBGTbPGH.jpg",
  "my-hero-academia": "https://image.tmdb.org/t/p/w500/vDHsLnOWKlPGmWs0kGfuhNF4w5l.jpg",
  "sword-art-online": "https://image.tmdb.org/t/p/w500/7GFXH9wuqXpJRnlFAMCJFqTqtqX.jpg",
  "re-zero": "https://image.tmdb.org/t/p/w500/aBIFMJMGVFnBnBJGqyBJBBBBBBB.jpg",
  "violet-evergarden": "https://image.tmdb.org/t/p/w500/ImvHbM4GsLtBBBBBBBBBBBBBBBB.jpg",
  "a-silent-voice": "https://image.tmdb.org/t/p/w500/tuFaWiqX0TXoWCJeOhFbbBBBBBBB.jpg",
  "the-garden-of-words": "https://image.tmdb.org/t/p/w500/BBBBBBBBBBBBBBBBBBBBBBBBBBB.jpg",
  "wolf-children": "https://image.tmdb.org/t/p/w500/BBBBBBBBBBBBBBBBBBBBBBBBBBB.jpg",
  "the-girl-who-leapt": "https://image.tmdb.org/t/p/w500/BBBBBBBBBBBBBBBBBBBBBBBBBBB.jpg",
  "5-centimeters": "https://image.tmdb.org/t/p/w500/BBBBBBBBBBBBBBBBBBBBBBBBBBB.jpg",
  "parasite": "https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
  "oldboy": "https://image.tmdb.org/t/p/w500/pWDtjs568ZfOTMbURQBYuT4Qxka.jpg",
  "train-to-busan": "https://image.tmdb.org/t/p/w500/oCOFIhCCCRKyAeGnFVCDFKwJVqS.jpg",
  "crash-landing-on-you": "https://image.tmdb.org/t/p/w500/BBBBBBBBBBBBBBBBBBBBBBBBBBB.jpg",
  "my-love-from-the-star": "https://image.tmdb.org/t/p/w500/BBBBBBBBBBBBBBBBBBBBBBBBBBB.jpg",
  "descendants-of-the-sun": "https://image.tmdb.org/t/p/w500/BBBBBBBBBBBBBBBBBBBBBBBBBBB.jpg",
  "goblin": "https://image.tmdb.org/t/p/w500/BBBBBBBBBBBBBBBBBBBBBBBBBBB.jpg",
  "its-okay-to-not-be-okay": "https://image.tmdb.org/t/p/w500/BBBBBBBBBBBBBBBBBBBBBBBBBBB.jpg",
  "vincenzo": "https://image.tmdb.org/t/p/w500/BBBBBBBBBBBBBBBBBBBBBBBBBBB.jpg",
  "business-proposal": "https://image.tmdb.org/t/p/w500/BBBBBBBBBBBBBBBBBBBBBBBBBBB.jpg",
  "extraordinary-attorney-woo": "https://image.tmdb.org/t/p/w500/BBBBBBBBBBBBBBBBBBBBBBBBBBB.jpg",
  "my-mister": "https://image.tmdb.org/t/p/w500/BBBBBBBBBBBBBBBBBBBBBBBBBBB.jpg",
  "reply-1988": "https://image.tmdb.org/t/p/w500/BBBBBBBBBBBBBBBBBBBBBBBBBBB.jpg",
};

export const GENRES = [
  'Fairytale', 'Musical', 'Romance', 'Adventure', 'Comedy',
  'Drama', 'Action', 'Family', 'Fantasy', 'Sci-Fi', 'War', 'Historical', 'Horror'
];

export const TYPES = [
  { id: 'movie', label: 'Movies', emoji: '🎬' },
  { id: 'animation', label: 'Animation', emoji: '🎈' },
  { id: 'series', label: 'Series', emoji: '📺' },
  { id: 'dorama', label: 'K-Drama', emoji: '🌸' },
  { id: 'anime', label: 'Anime', emoji: '⛩️' },
];

// Color palettes for movie cards
export const PALETTES = {
  peach: ['#ffd6c0', '#ffc0cb'],
  mint: ['#c8f5d0', '#c0e8ff'],
  lav: ['#d4c5f9', '#c0e8ff'],
  butter: ['#fff3b0', '#ffd6c0'],
  rose: ['#ffc0cb', '#d4c5f9'],
  sky: ['#c0e8ff', '#c8f5d0'],
};

export const MOVIES: Movie[] = [
  // Animation - Disney Classics
  { id: 'cinderella', title: 'Cinderella', year: 1950, runtime: 74, emoji: '👠', kind: 'animation', tags: ['disney', 'princess', 'classic', 'fairytale', 'musical', 'romance'] },
  { id: 'snow-white', title: 'Snow White', year: 1937, runtime: 83, emoji: '🍎', kind: 'animation', tags: ['disney', 'princess', 'classic', 'fairytale', 'musical'] },
  { id: 'little-mermaid', title: 'The Little Mermaid', year: 1989, runtime: 83, emoji: '🧜', kind: 'animation', tags: ['disney', 'princess', 'fairytale', 'musical', 'romance'] },
  { id: 'beauty-beast', title: 'Beauty and the Beast', year: 1991, runtime: 84, emoji: '🌹', kind: 'animation', tags: ['disney', 'princess', 'fairytale', 'musical', 'romance'] },
  { id: 'aladdin', title: 'Aladdin', year: 1992, runtime: 90, emoji: '🪔', kind: 'animation', tags: ['disney', 'musical', 'fairytale', 'adventure'] },
  { id: 'lion-king', title: 'The Lion King', year: 1994, runtime: 88, emoji: '🦁', kind: 'animation', tags: ['disney', 'musical', 'adventure', 'family'] },
  { id: 'mulan', title: 'Mulan', year: 1998, runtime: 88, emoji: '🐉', kind: 'animation', tags: ['disney', 'princess', 'adventure', 'musical'] },
  { id: 'pocahontas', title: 'Pocahontas', year: 1995, runtime: 81, emoji: '🍃', kind: 'animation', tags: ['disney', 'princess', 'musical', 'romance'] },
  { id: 'tangled', title: 'Tangled', year: 2010, runtime: 100, emoji: '🌟', kind: 'animation', tags: ['disney', 'princess', 'fairytale', 'musical', 'romance'] },
  { id: 'frozen', title: 'Frozen', year: 2013, runtime: 102, emoji: '❄️', kind: 'animation', tags: ['disney', 'princess', 'musical', 'family'] },
  { id: 'moana', title: 'Moana', year: 2016, runtime: 107, emoji: '🌊', kind: 'animation', tags: ['disney', 'princess', 'musical', 'adventure'] },
  { id: 'encanto', title: 'Encanto', year: 2021, runtime: 102, emoji: '🦋', kind: 'animation', tags: ['disney', 'family', 'musical'] },
  { id: 'raya', title: 'Raya and the Last Dragon', year: 2021, runtime: 107, emoji: '🐉', kind: 'animation', tags: ['disney', 'adventure', 'fantasy', 'family'] },
  { id: 'wish', title: 'Wish', year: 2023, runtime: 95, emoji: '⭐', kind: 'animation', tags: ['disney', 'musical', 'fantasy', 'family'] },
  // Pixar
  { id: 'toy-story', title: 'Toy Story', year: 1995, runtime: 81, emoji: '🤠', kind: 'animation', tags: ['pixar', 'family', 'adventure', 'comedy'] },
  { id: 'finding-nemo', title: 'Finding Nemo', year: 2003, runtime: 100, emoji: '🐠', kind: 'animation', tags: ['pixar', 'family', 'adventure'] },
  { id: 'up', title: 'Up', year: 2009, runtime: 96, emoji: '🎈', kind: 'animation', tags: ['pixar', 'family', 'adventure', 'drama'] },
  { id: 'wall-e', title: 'WALL·E', year: 2008, runtime: 98, emoji: '🤖', kind: 'animation', tags: ['pixar', 'family', 'romance', 'sci-fi'] },
  { id: 'ratatouille', title: 'Ratatouille', year: 2007, runtime: 111, emoji: '🐭', kind: 'animation', tags: ['pixar', 'family', 'comedy'] },
  { id: 'inside-out', title: 'Inside Out', year: 2015, runtime: 95, emoji: '🧠', kind: 'animation', tags: ['pixar', 'family', 'drama'] },
  { id: 'coco', title: 'Coco', year: 2017, runtime: 105, emoji: '🎸', kind: 'animation', tags: ['pixar', 'family', 'musical', 'drama'] },
  { id: 'soul', title: 'Soul', year: 2020, runtime: 100, emoji: '🎹', kind: 'animation', tags: ['pixar', 'family', 'drama'] },
  { id: 'luca', title: 'Luca', year: 2021, runtime: 95, emoji: '🦎', kind: 'animation', tags: ['pixar', 'family', 'adventure', 'comedy'] },
  { id: 'turning-red', title: 'Turning Red', year: 2022, runtime: 100, emoji: '🐼', kind: 'animation', tags: ['pixar', 'family', 'comedy'] },
  { id: 'elemental', title: 'Elemental', year: 2023, runtime: 101, emoji: '🔥', kind: 'animation', tags: ['pixar', 'family', 'romance'] },
  { id: 'the-incredibles', title: 'The Incredibles', year: 2004, runtime: 115, emoji: '🦸', kind: 'animation', tags: ['pixar', 'family', 'action', 'adventure'] },
  { id: 'brave', title: 'Brave', year: 2012, runtime: 93, emoji: '🏹', kind: 'animation', tags: ['pixar', 'princess', 'adventure', 'family'] },
  { id: 'monsters-inc', title: "Monsters, Inc.", year: 2001, runtime: 92, emoji: '👾', kind: 'animation', tags: ['pixar', 'family', 'comedy', 'adventure'] },
  { id: 'cars', title: 'Cars', year: 2006, runtime: 117, emoji: '🚗', kind: 'animation', tags: ['pixar', 'family', 'adventure', 'comedy'] },
  // Studio Ghibli
  { id: 'spirited-away', title: 'Spirited Away', year: 2001, runtime: 125, emoji: '🐉', kind: 'animation', tags: ['ghibli', 'anime', 'fairytale', 'adventure'] },
  { id: 'totoro', title: 'My Neighbor Totoro', year: 1988, runtime: 86, emoji: '🌳', kind: 'animation', tags: ['ghibli', 'anime', 'family', 'fantasy'] },
  { id: 'howls-moving-castle', title: "Howl's Moving Castle", year: 2004, runtime: 119, emoji: '🏰', kind: 'animation', tags: ['ghibli', 'anime', 'fantasy', 'romance', 'adventure'] },
  { id: 'princess-mononoke', title: 'Princess Mononoke', year: 1997, runtime: 134, emoji: '🐺', kind: 'animation', tags: ['ghibli', 'anime', 'adventure', 'fantasy', 'drama'] },
  { id: 'kiki', title: "Kiki's Delivery Service", year: 1989, runtime: 103, emoji: '🧹', kind: 'animation', tags: ['ghibli', 'anime', 'fairytale', 'adventure'] },
  { id: 'nausicaa', title: 'Nausicaä of the Valley of the Wind', year: 1984, runtime: 117, emoji: '🌬️', kind: 'animation', tags: ['ghibli', 'anime', 'adventure', 'sci-fi', 'fantasy'] },
  { id: 'castle-sky', title: 'Castle in the Sky', year: 1986, runtime: 124, emoji: '🏯', kind: 'animation', tags: ['ghibli', 'anime', 'adventure', 'fantasy'] },
  { id: 'ponyo', title: 'Ponyo', year: 2008, runtime: 101, emoji: '🐟', kind: 'animation', tags: ['ghibli', 'anime', 'fairytale', 'family'] },
  { id: 'grave-fireflies', title: 'Grave of the Fireflies', year: 1988, runtime: 89, emoji: '🌟', kind: 'animation', tags: ['ghibli', 'anime', 'drama', 'war', 'historical'] },
  // Other animation
  { id: 'shrek', title: 'Shrek', year: 2001, runtime: 90, emoji: '🟢', kind: 'animation', tags: ['comedy', 'fairytale', 'adventure', 'romance'] },
  { id: 'shrek-2', title: 'Shrek 2', year: 2004, runtime: 93, emoji: '🟢', kind: 'animation', tags: ['comedy', 'fairytale', 'adventure', 'romance'] },
  { id: 'kung-fu-panda', title: 'Kung Fu Panda', year: 2008, runtime: 92, emoji: '🐼', kind: 'animation', tags: ['comedy', 'adventure', 'action', 'family'] },
  { id: 'how-to-train-your-dragon', title: 'How to Train Your Dragon', year: 2010, runtime: 98, emoji: '🐲', kind: 'animation', tags: ['adventure', 'fantasy', 'family'] },
  { id: 'despicable-me', title: 'Despicable Me', year: 2010, runtime: 95, emoji: '💛', kind: 'animation', tags: ['comedy', 'family', 'adventure'] },
  { id: 'zootopia', title: 'Zootopia', year: 2016, runtime: 108, emoji: '🦊', kind: 'animation', tags: ['adventure', 'comedy', 'family', 'drama'] },
  { id: 'wreck-it-ralph', title: 'Wreck-It Ralph', year: 2012, runtime: 101, emoji: '🕹️', kind: 'animation', tags: ['adventure', 'comedy', 'family'] },
  { id: 'big-hero-6', title: 'Big Hero 6', year: 2014, runtime: 102, emoji: '🤖', kind: 'animation', tags: ['adventure', 'action', 'family', 'sci-fi'] },
  // Movies - Action/Adventure
  { id: 'avatar', title: 'Avatar', year: 2009, runtime: 162, emoji: '🌿', kind: 'movie', tags: ['sci-fi', 'adventure', 'action', 'fantasy'] },
  { id: 'titanic', title: 'Titanic', year: 1997, runtime: 194, emoji: '🚢', kind: 'movie', tags: ['romance', 'drama', 'historical'] },
  { id: 'inception', title: 'Inception', year: 2010, runtime: 148, emoji: '🌀', kind: 'movie', tags: ['sci-fi', 'action', 'adventure', 'drama'] },
  { id: 'interstellar', title: 'Interstellar', year: 2014, runtime: 169, emoji: '🌌', kind: 'movie', tags: ['sci-fi', 'adventure', 'drama'] },
  { id: 'the-dark-knight', title: 'The Dark Knight', year: 2008, runtime: 152, emoji: '🦇', kind: 'movie', tags: ['action', 'drama'] },
  { id: 'forrest-gump', title: 'Forrest Gump', year: 1994, runtime: 142, emoji: '🏃', kind: 'movie', tags: ['drama', 'romance', 'comedy', 'historical'] },
  { id: 'the-shawshank-redemption', title: 'The Shawshank Redemption', year: 1994, runtime: 142, emoji: '🔓', kind: 'movie', tags: ['drama'] },
  { id: 'schindlers-list', title: "Schindler's List", year: 1993, runtime: 195, emoji: '📋', kind: 'movie', tags: ['drama', 'historical', 'war'] },
  { id: 'the-godfather', title: 'The Godfather', year: 1972, runtime: 175, emoji: '🌹', kind: 'movie', tags: ['drama', 'action'] },
  { id: 'pulp-fiction', title: 'Pulp Fiction', year: 1994, runtime: 154, emoji: '💼', kind: 'movie', tags: ['action', 'drama', 'comedy'] },
  { id: 'the-matrix', title: 'The Matrix', year: 1999, runtime: 136, emoji: '💊', kind: 'movie', tags: ['sci-fi', 'action', 'adventure'] },
  { id: 'gladiator', title: 'Gladiator', year: 2000, runtime: 155, emoji: '⚔️', kind: 'movie', tags: ['action', 'drama', 'historical', 'adventure'] },
  { id: 'fight-club', title: 'Fight Club', year: 1999, runtime: 139, emoji: '👊', kind: 'movie', tags: ['drama', 'action'] },
  { id: 'goodfellas', title: 'Goodfellas', year: 1990, runtime: 146, emoji: '🔫', kind: 'movie', tags: ['drama', 'action'] },
  { id: 'jurassic-park', title: 'Jurassic Park', year: 1993, runtime: 127, emoji: '🦕', kind: 'movie', tags: ['sci-fi', 'adventure', 'action'] },
  { id: 'home-alone', title: 'Home Alone', year: 1990, runtime: 103, emoji: '🏠', kind: 'movie', tags: ['comedy', 'family', 'adventure'] },
  // Marvel
  { id: 'avengers-endgame', title: 'Avengers: Endgame', year: 2019, runtime: 181, emoji: '🦸', kind: 'movie', tags: ['action', 'adventure', 'sci-fi', 'fantasy'] },
  { id: 'avengers-infinity-war', title: 'Avengers: Infinity War', year: 2018, runtime: 149, emoji: '🌌', kind: 'movie', tags: ['action', 'adventure', 'sci-fi', 'fantasy'] },
  { id: 'iron-man', title: 'Iron Man', year: 2008, runtime: 126, emoji: '🤖', kind: 'movie', tags: ['action', 'adventure', 'sci-fi'] },
  { id: 'black-panther', title: 'Black Panther', year: 2018, runtime: 134, emoji: '🐆', kind: 'movie', tags: ['action', 'adventure', 'sci-fi', 'fantasy'] },
  { id: 'spider-man-no-way-home', title: 'Spider-Man: No Way Home', year: 2021, runtime: 148, emoji: '🕷️', kind: 'movie', tags: ['action', 'adventure', 'sci-fi', 'fantasy'] },
  { id: 'thor-ragnarok', title: 'Thor: Ragnarok', year: 2017, runtime: 130, emoji: '⚡', kind: 'movie', tags: ['action', 'adventure', 'comedy', 'fantasy'] },
  { id: 'guardians-galaxy', title: 'Guardians of the Galaxy', year: 2014, runtime: 121, emoji: '🚀', kind: 'movie', tags: ['action', 'adventure', 'comedy', 'sci-fi'] },
  { id: 'doctor-strange', title: 'Doctor Strange', year: 2016, runtime: 115, emoji: '🔮', kind: 'movie', tags: ['action', 'adventure', 'fantasy', 'sci-fi'] },
  { id: 'the-avengers', title: 'The Avengers', year: 2012, runtime: 143, emoji: '⚡', kind: 'movie', tags: ['action', 'adventure', 'sci-fi', 'fantasy'] },
  // DC
  { id: 'wonder-woman', title: 'Wonder Woman', year: 2017, runtime: 141, emoji: '⚔️', kind: 'movie', tags: ['action', 'adventure', 'fantasy', 'war'] },
  { id: 'joker', title: 'Joker', year: 2019, runtime: 122, emoji: '🃏', kind: 'movie', tags: ['drama', 'action'] },
  { id: 'batman-begins', title: 'Batman Begins', year: 2005, runtime: 140, emoji: '🦇', kind: 'movie', tags: ['action', 'adventure', 'drama'] },
  // Star Wars
  { id: 'star-wars-new-hope', title: 'Star Wars: A New Hope', year: 1977, runtime: 121, emoji: '⭐', kind: 'movie', tags: ['sci-fi', 'adventure', 'action', 'fantasy'] },
  { id: 'star-wars-empire', title: 'The Empire Strikes Back', year: 1980, runtime: 124, emoji: '🌑', kind: 'movie', tags: ['sci-fi', 'adventure', 'action', 'fantasy'] },
  { id: 'star-wars-return', title: 'Return of the Jedi', year: 1983, runtime: 131, emoji: '🌟', kind: 'movie', tags: ['sci-fi', 'adventure', 'action', 'fantasy'] },
  { id: 'star-wars-force-awakens', title: 'The Force Awakens', year: 2015, runtime: 138, emoji: '⚡', kind: 'movie', tags: ['sci-fi', 'adventure', 'action', 'fantasy'] },
  { id: 'rogue-one', title: 'Rogue One', year: 2016, runtime: 133, emoji: '🔫', kind: 'movie', tags: ['sci-fi', 'adventure', 'action', 'war'] },
  // LOTR / Harry Potter
  { id: 'the-lord-of-the-rings-fellowship', title: 'The Fellowship of the Ring', year: 2001, runtime: 178, emoji: '💍', kind: 'movie', tags: ['adventure', 'fantasy', 'drama', 'action'] },
  { id: 'the-lord-of-the-rings-two-towers', title: 'The Two Towers', year: 2002, runtime: 179, emoji: '🗼', kind: 'movie', tags: ['adventure', 'fantasy', 'drama', 'action', 'war'] },
  { id: 'the-lord-of-the-rings-return', title: 'The Return of the King', year: 2003, runtime: 201, emoji: '👑', kind: 'movie', tags: ['adventure', 'fantasy', 'drama', 'action', 'war'] },
  { id: 'harry-potter-sorcerers-stone', title: "Harry Potter and the Sorcerer's Stone", year: 2001, runtime: 152, emoji: '🧙', kind: 'movie', tags: ['fantasy', 'adventure', 'family'] },
  { id: 'harry-potter-chamber', title: 'Harry Potter and the Chamber of Secrets', year: 2002, runtime: 161, emoji: '🐍', kind: 'movie', tags: ['fantasy', 'adventure', 'family'] },
  { id: 'harry-potter-prisoner', title: 'Harry Potter and the Prisoner of Azkaban', year: 2004, runtime: 142, emoji: '🐺', kind: 'movie', tags: ['fantasy', 'adventure', 'family'] },
  { id: 'harry-potter-goblet', title: 'Harry Potter and the Goblet of Fire', year: 2005, runtime: 157, emoji: '🔥', kind: 'movie', tags: ['fantasy', 'adventure', 'family'] },
  { id: 'harry-potter-order', title: 'Harry Potter and the Order of the Phoenix', year: 2007, runtime: 138, emoji: '🦅', kind: 'movie', tags: ['fantasy', 'adventure', 'family'] },
  { id: 'harry-potter-half-blood', title: 'Harry Potter and the Half-Blood Prince', year: 2009, runtime: 153, emoji: '📖', kind: 'movie', tags: ['fantasy', 'adventure', 'family'] },
  { id: 'harry-potter-deathly-hallows-1', title: 'Harry Potter and the Deathly Hallows Part 1', year: 2010, runtime: 146, emoji: '⚡', kind: 'movie', tags: ['fantasy', 'adventure', 'drama'] },
  { id: 'harry-potter-deathly-hallows-2', title: 'Harry Potter and the Deathly Hallows Part 2', year: 2011, runtime: 130, emoji: '⚡', kind: 'movie', tags: ['fantasy', 'adventure', 'drama', 'action'] },
  // Romance
  { id: 'la-la-land', title: 'La La Land', year: 2016, runtime: 128, emoji: '🌆', kind: 'movie', tags: ['romance', 'musical', 'drama'] },
  { id: 'the-notebook', title: 'The Notebook', year: 2004, runtime: 123, emoji: '📓', kind: 'movie', tags: ['romance', 'drama'] },
  { id: 'pride-and-prejudice', title: 'Pride & Prejudice', year: 2005, runtime: 129, emoji: '🌹', kind: 'movie', tags: ['romance', 'drama', 'historical'] },
  { id: 'love-actually', title: 'Love Actually', year: 2003, runtime: 135, emoji: '❤️', kind: 'movie', tags: ['romance', 'comedy', 'drama'] },
  { id: 'crazy-rich-asians', title: 'Crazy Rich Asians', year: 2018, runtime: 120, emoji: '💎', kind: 'movie', tags: ['romance', 'comedy', 'drama'] },
  { id: 'to-all-the-boys', title: 'To All the Boys I\'ve Loved Before', year: 2018, runtime: 99, emoji: '💌', kind: 'movie', tags: ['romance', 'comedy'] },
  // Comedy
  { id: 'mean-girls', title: 'Mean Girls', year: 2004, runtime: 97, emoji: '💅', kind: 'movie', tags: ['comedy', 'drama'] },
  { id: 'legally-blonde', title: 'Legally Blonde', year: 2001, runtime: 96, emoji: '👱', kind: 'movie', tags: ['comedy', 'romance', 'drama'] },
  { id: 'the-proposal', title: 'The Proposal', year: 2009, runtime: 108, emoji: '💍', kind: 'movie', tags: ['comedy', 'romance'] },
  // Musicals
  { id: 'bohemian-rhapsody', title: 'Bohemian Rhapsody', year: 2018, runtime: 134, emoji: '🎸', kind: 'movie', tags: ['drama', 'musical', 'historical'] },
  { id: 'the-greatest-showman', title: 'The Greatest Showman', year: 2017, runtime: 105, emoji: '🎪', kind: 'movie', tags: ['musical', 'drama', 'historical'] },
  { id: 'mamma-mia', title: 'Mamma Mia!', year: 2008, runtime: 108, emoji: '🎵', kind: 'movie', tags: ['musical', 'romance', 'comedy'] },
  { id: 'grease', title: 'Grease', year: 1978, runtime: 110, emoji: '🎶', kind: 'movie', tags: ['musical', 'romance', 'comedy'] },
  // Hunger Games
  { id: 'the-hunger-games', title: 'The Hunger Games', year: 2012, runtime: 142, emoji: '🏹', kind: 'movie', tags: ['action', 'adventure', 'sci-fi', 'drama'] },
  { id: 'catching-fire', title: 'Catching Fire', year: 2013, runtime: 146, emoji: '🔥', kind: 'movie', tags: ['action', 'adventure', 'sci-fi', 'drama'] },
  // Parasite / Asian cinema
  { id: 'parasite', title: 'Parasite', year: 2019, runtime: 132, emoji: '🏠', kind: 'movie', tags: ['drama', 'comedy', 'horror'] },
  { id: 'oldboy', title: 'Oldboy', year: 2003, runtime: 120, emoji: '🔨', kind: 'movie', tags: ['drama', 'action', 'horror'] },
  { id: 'train-to-busan', title: 'Train to Busan', year: 2016, runtime: 118, emoji: '🚂', kind: 'movie', tags: ['horror', 'action', 'drama'] },
  // Anime movies
  { id: 'your-name', title: 'Your Name', year: 2016, runtime: 106, emoji: '🌠', kind: 'anime', tags: ['romance', 'fantasy', 'drama'] },
  { id: 'weathering-with-you', title: 'Weathering with You', year: 2019, runtime: 112, emoji: '☀️', kind: 'anime', tags: ['romance', 'fantasy', 'drama'] },
  { id: 'suzume', title: 'Suzume', year: 2022, runtime: 122, emoji: '🚪', kind: 'anime', tags: ['adventure', 'fantasy', 'romance', 'drama'] },
  { id: 'a-silent-voice', title: 'A Silent Voice', year: 2016, runtime: 130, emoji: '🤫', kind: 'anime', tags: ['drama', 'romance'] },
  // Anime series
  { id: 'attack-on-titan', title: 'Attack on Titan', year: 2013, runtime: 1440, emoji: '⚔️', kind: 'anime', tags: ['action', 'drama', 'fantasy', 'horror', 'war'] },
  { id: 'death-note', title: 'Death Note', year: 2006, runtime: 600, emoji: '📓', kind: 'anime', tags: ['drama', 'fantasy', 'horror'] },
  { id: 'fullmetal-alchemist', title: 'Fullmetal Alchemist: Brotherhood', year: 2009, runtime: 1500, emoji: '⚗️', kind: 'anime', tags: ['adventure', 'action', 'drama', 'fantasy'] },
  { id: 'naruto', title: 'Naruto', year: 2002, runtime: 5400, emoji: '🍥', kind: 'anime', tags: ['action', 'adventure', 'comedy', 'drama'] },
  { id: 'one-piece', title: 'One Piece', year: 1999, runtime: 18000, emoji: '🏴‍☠️', kind: 'anime', tags: ['action', 'adventure', 'comedy', 'fantasy'] },
  { id: 'demon-slayer', title: 'Demon Slayer', year: 2019, runtime: 720, emoji: '🗡️', kind: 'anime', tags: ['action', 'adventure', 'fantasy', 'drama'] },
  { id: 'jujutsu-kaisen', title: 'Jujutsu Kaisen', year: 2020, runtime: 600, emoji: '👁️', kind: 'anime', tags: ['action', 'adventure', 'fantasy', 'horror'] },
  { id: 'my-hero-academia', title: 'My Hero Academia', year: 2016, runtime: 2400, emoji: '🦸', kind: 'anime', tags: ['action', 'adventure', 'comedy', 'drama'] },
  { id: 'sword-art-online', title: 'Sword Art Online', year: 2012, runtime: 1200, emoji: '⚔️', kind: 'anime', tags: ['action', 'adventure', 'romance', 'sci-fi', 'fantasy'] },
  { id: 'violet-evergarden', title: 'Violet Evergarden', year: 2018, runtime: 540, emoji: '✉️', kind: 'anime', tags: ['drama', 'romance', 'fantasy', 'historical'] },
  // K-Drama
  { id: 'crash-landing-on-you', title: 'Crash Landing on You', year: 2019, runtime: 1080, emoji: '🪂', kind: 'dorama', tags: ['romance', 'drama', 'comedy'] },
  { id: 'my-love-from-the-star', title: 'My Love from the Star', year: 2013, runtime: 960, emoji: '⭐', kind: 'dorama', tags: ['romance', 'drama', 'fantasy', 'comedy'] },
  { id: 'descendants-of-the-sun', title: 'Descendants of the Sun', year: 2016, runtime: 960, emoji: '☀️', kind: 'dorama', tags: ['romance', 'drama', 'action', 'war'] },
  { id: 'goblin', title: 'Goblin', year: 2016, runtime: 960, emoji: '👺', kind: 'dorama', tags: ['romance', 'drama', 'fantasy'] },
  { id: 'its-okay-to-not-be-okay', title: "It's Okay to Not Be Okay", year: 2020, runtime: 960, emoji: '🌸', kind: 'dorama', tags: ['romance', 'drama'] },
  { id: 'vincenzo', title: 'Vincenzo', year: 2021, runtime: 1320, emoji: '🤵', kind: 'dorama', tags: ['action', 'drama', 'comedy', 'romance'] },
  { id: 'business-proposal', title: 'A Business Proposal', year: 2022, runtime: 720, emoji: '💼', kind: 'dorama', tags: ['romance', 'comedy', 'drama'] },
  { id: 'extraordinary-attorney-woo', title: 'Extraordinary Attorney Woo', year: 2022, runtime: 960, emoji: '🐋', kind: 'dorama', tags: ['drama', 'comedy', 'romance'] },
  { id: 'squid-game', title: 'Squid Game', year: 2021, runtime: 540, emoji: '🦑', kind: 'dorama', tags: ['drama', 'action', 'horror'] },
  { id: 'reply-1988', title: 'Reply 1988', year: 2015, runtime: 2880, emoji: '📺', kind: 'dorama', tags: ['drama', 'comedy', 'romance', 'historical'] },
  // Western Series
  { id: 'breaking-bad', title: 'Breaking Bad', year: 2008, runtime: 2970, emoji: '⚗️', kind: 'series', tags: ['drama', 'action'] },
  { id: 'game-of-thrones', title: 'Game of Thrones', year: 2011, runtime: 4380, emoji: '👑', kind: 'series', tags: ['drama', 'action', 'fantasy', 'war'] },
  { id: 'stranger-things', title: 'Stranger Things', year: 2016, runtime: 2160, emoji: '🔦', kind: 'series', tags: ['sci-fi', 'horror', 'drama', 'adventure'] },
  { id: 'the-office', title: 'The Office', year: 2005, runtime: 3600, emoji: '💼', kind: 'series', tags: ['comedy', 'drama', 'romance'] },
  { id: 'friends', title: 'Friends', year: 1994, runtime: 5040, emoji: '☕', kind: 'series', tags: ['comedy', 'romance', 'drama'] },
  { id: 'the-crown', title: 'The Crown', year: 2016, runtime: 3000, emoji: '👑', kind: 'series', tags: ['drama', 'historical', 'romance'] },
  { id: 'money-heist', title: 'Money Heist', year: 2017, runtime: 2400, emoji: '💰', kind: 'series', tags: ['action', 'drama', 'romance'] },
  { id: 'dark', title: 'Dark', year: 2017, runtime: 1620, emoji: '🌑', kind: 'series', tags: ['sci-fi', 'drama', 'horror'] },
  { id: 'black-mirror', title: 'Black Mirror', year: 2011, runtime: 1800, emoji: '📱', kind: 'series', tags: ['sci-fi', 'drama', 'horror'] },
  { id: 'the-witcher', title: 'The Witcher', year: 2019, runtime: 1440, emoji: '⚔️', kind: 'series', tags: ['action', 'adventure', 'fantasy', 'drama'] },
  { id: 'wednesday', title: 'Wednesday', year: 2022, runtime: 480, emoji: '🖤', kind: 'series', tags: ['horror', 'comedy', 'mystery', 'fantasy'] },
  { id: 'emily-in-paris', title: 'Emily in Paris', year: 2020, runtime: 960, emoji: '🗼', kind: 'series', tags: ['comedy', 'romance', 'drama'] },
  { id: 'bridgerton', title: 'Bridgerton', year: 2020, runtime: 960, emoji: '🌸', kind: 'series', tags: ['romance', 'drama', 'historical'] },
  { id: 'the-queens-gambit', title: "The Queen's Gambit", year: 2020, runtime: 420, emoji: '♟️', kind: 'series', tags: ['drama', 'historical'] },
  { id: 'ted-lasso', title: 'Ted Lasso', year: 2020, runtime: 1440, emoji: '⚽', kind: 'series', tags: ['comedy', 'drama', 'romance'] },
  { id: 'succession', title: 'Succession', year: 2018, runtime: 2400, emoji: '💰', kind: 'series', tags: ['drama', 'comedy'] },
  { id: 'euphoria', title: 'Euphoria', year: 2019, runtime: 960, emoji: '✨', kind: 'series', tags: ['drama'] },
  { id: 'sex-education', title: 'Sex Education', year: 2019, runtime: 1440, emoji: '📚', kind: 'series', tags: ['comedy', 'drama', 'romance'] },
  { id: 'the-mandalorian', title: 'The Mandalorian', year: 2019, runtime: 960, emoji: '🪖', kind: 'series', tags: ['action', 'adventure', 'sci-fi', 'fantasy'] },
  { id: 'loki', title: 'Loki', year: 2021, runtime: 360, emoji: '🐍', kind: 'series', tags: ['action', 'adventure', 'sci-fi', 'fantasy'] },
  { id: 'wandavision', title: 'WandaVision', year: 2021, runtime: 360, emoji: '🔮', kind: 'series', tags: ['action', 'drama', 'sci-fi', 'fantasy'] },
  { id: 'the-boys', title: 'The Boys', year: 2019, runtime: 1440, emoji: '💥', kind: 'series', tags: ['action', 'drama', 'comedy', 'sci-fi'] },
  { id: 'invincible', title: 'Invincible', year: 2021, runtime: 480, emoji: '🦸', kind: 'series', tags: ['action', 'adventure', 'drama', 'sci-fi'] },
  { id: 'arcane', title: 'Arcane', year: 2021, runtime: 540, emoji: '⚡', kind: 'series', tags: ['action', 'adventure', 'fantasy', 'drama'] },
  { id: 'mindhunter', title: 'Mindhunter', year: 2017, runtime: 1200, emoji: '🔍', kind: 'series', tags: ['drama', 'horror'] },
];

export function getPoster(id: string): string | undefined {
  return POSTER_MAP[id];
}

export function formatRuntime(minutes: number): string {
  if (minutes < 60) return `${minutes}m`;
  const h = Math.floor(minutes / 60);
  const m = minutes % 60;
  if (m === 0) return `${h}h`;
  return `${h}h ${m}m`;
}

export function formatHours(minutes: number): string {
  const h = (minutes / 60).toFixed(1);
  return `${h}h`;
}
