export type MovieKind = 'movie' | 'animation' | 'series' | 'dorama' | 'anime';

export interface Movie {
  id: string;
  title: string;
  year: number;
  runtime: number;
  emoji: string;
  kind: MovieKind;
  tags: string[];
}

const T = (path: string) => `https://image.tmdb.org/t/p/w500${path}`;

export const POSTER_MAP: Record<string, string> = {
  // Disney Animation
  "cinderella":              T("/ug3ndicuPM1V07vhVFGLMsd4AZl.jpg"),
  "snow-white":              T("/3VAHfuNb6Z7UiW12iYKANSPBl8m.jpg"),
  "little-mermaid":          T("/plcZXvI310FkbwIptvd6rqk63LP.jpg"),
  "beauty-beast":            T("/hUJ0UvQ5tgE2Z9WpfuduVSdiCiU.jpg"),
  "aladdin":                 T("/eLFfl7vS8dkeG1hKp5mwbm37V83.jpg"),
  "lion-king":               T("/sKCr78MXSLixwmZ8DyJLrpMsd15.jpg"),
  "mulan":                   T("/eDCblCfqFqJPpMnTnGxQxCFWYqJ.jpg"),
  "pocahontas":              T("/6PBIFsJRGBGvNFGnOKPJzQBJnFB.jpg"),
  "tangled":                 T("/uX7LXnsC7bZJZjn048UCOwkPXWJ.jpg"),
  "frozen":                  T("/kgwjIb2JDHRhNk13lmSxiClFjVk.jpg"),
  "moana":                   T("/inVq3FRqcYIRl2la8iZikYYxFNR.jpg"),
  "encanto":                 T("/4j0PNHkMr5ax3IA8tjtxcmPU3QT.jpg"),
  "raya":                    T("/lPsD10PP4rgUGiGR4CCXA6iY0QQ.jpg"),
  "wish":                    T("/AcoVfiv1rrWOmAdpnAMnM56ki19.jpg"),
  // Pixar
  "toy-story":               T("/uXDfjJbdP4ijW5hWSBrPl9KcertP.jpg"),
  "finding-nemo":            T("/eHuGQ10FUzK1mdOY69wF5pGgEf5.jpg"),
  "up":                      T("/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg"),
  "wall-e":                  T("/hbhFnRzzg6ZDmm8YAmxBnQpQIPh.jpg"),
  "ratatouille":             T("/npHNjldbeTHdKKw28bJKs7lzqzj.jpg"),
  "inside-out":              T("/2H1TmgdfNtsKlU9jKdeNyYL5y8T.jpg"),
  "coco":                    T("/gGEsBPAijhVUFoiNpgZXqRVWJt2.jpg"),
  "soul":                    T("/hm58n7uhlmjZHHfAll3gTorczkn.jpg"),
  "luca":                    T("/jTswp6KyDYKtvC52GbHagrZbGvD.jpg"),
  "turning-red":             T("/qSb7nPeta7VFlkQovvZ5NiZDpK5.jpg"),
  "elemental":               T("/6oH378KUfCEitzJkm07r97L0RsZ.jpg"),
  "the-incredibles":         T("/2LqaLgk4Z226KkgPJuiOQ58ShKD.jpg"),
  "brave":                   T("/A4qnCFMBpnBsGlLmVlpGMKJBpnH.jpg"),
  "monsters-inc":            T("/sgheSKxZkttIe8ONaJd2iswVtpq.jpg"),
  "cars":                    T("/uGBVAWjjA55V6UyhPLHkqbf7Bum.jpg"),
  // Ghibli
  "spirited-away":           T("/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg"),
  "totoro":                  T("/rtGDOeG9LzoerkDGZF9dnVeLppL.jpg"),
  "howls-moving-castle":     T("/TkTP5VFKe4r0UXZC0bBXMGcAZj.jpg"),
  "princess-mononoke":       T("/jHa6GxMzsNIBBMBbhJAEzPn76mK.jpg"),
  "kiki":                    T("/dL11DBPcRhWWnJcFXl9A07MrqTI.jpg"),
  "nausicaa":                T("/pgkFBpnMNJVxMFHGJXJTKCmBJxs.jpg"),
  "castle-sky":              T("/npFQnlZaHNgAqNIAOqzHFKQMnYo.jpg"),
  "ponyo":                   T("/yvNLBnCoE4iGzmBMHwBstMs8Ber.jpg"),
  "grave-fireflies":         T("/k9tv1rXZbOhH7eiCk378x61kNQ1.jpg"),
  // Anime movies
  "your-name":               T("/q719jXXEzOoYaps6babgKnONONX.jpg"),
  "weathering-with-you":     T("/mIBCtPvKZQlxubxKMeViO2UrP3q.jpg"),
  "suzume":                  T("/jHa6GxMzsNIBBMBbhJAEzPn76mK.jpg"),
  "a-silent-voice":          T("/xUfRZu2mi8jH6SzQEJGP6tjBuYj.jpg"),
  // Other animation
  "shrek":                   T("/iB64vpL3dIObOtMZgX3RqdVdQDc.jpg"),
  "shrek-2":                 T("/2yYP0PQjG8zVqturh1BAqu2Tixl.jpg"),
  "kung-fu-panda":           T("/wWt5mnF0oPc7lZbOqOBfVhTdoKD.jpg"),
  "how-to-train-your-dragon":T("/oKT4NNlw1etqoGeBPxAle0MXj4a.jpg"),
  "despicable-me":           T("/9lOloREsAqBPi8iAntwmqFeLZer.jpg"),
  "zootopia":                T("/sM33SANp9z6rXW8Itn7NnG1GOEs.jpg"),
  "wreck-it-ralph":          T("/a7AoS8NNMEsHDIoGahkzjupFtGl.jpg"),
  "big-hero-6":              T("/bHarw8xrmQeqf3t8HpgTODaKFJu.jpg"),
  // Movies
  "avatar":                  T("/jRXYjXNq0Cs2TcJjLkki24MLp7u.jpg"),
  "titanic":                 T("/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg"),
  "inception":               T("/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg"),
  "interstellar":            T("/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg"),
  "the-dark-knight":         T("/qJ2tW6WMUDux911r6m7haRef0WH.jpg"),
  "forrest-gump":            T("/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg"),
  "the-shawshank-redemption":T("/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg"),
  "schindlers-list":         T("/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg"),
  "the-godfather":           T("/3bhkrj58Vtu7enYsLLeHCcAqDRb.jpg"),
  "pulp-fiction":            T("/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg"),
  "the-matrix":              T("/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg"),
  "gladiator":               T("/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg"),
  "fight-club":              T("/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg"),
  "goodfellas":              T("/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg"),
  "jurassic-park":           T("/oU7Oq2kFAAlGqbU4VoAE36g4hoI.jpg"),
  "home-alone":              T("/onTSipZ8R3bliBdKfPtsDuHTdlL.jpg"),
  "the-lion-king-2019":      T("/2bXbqYdUdNVa8VIWXVfclP2ICtT.jpg"),
  // Marvel
  "avengers-endgame":        T("/or06FN3Dka5tukK1e9sl16pB3iy.jpg"),
  "avengers-infinity-war":   T("/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg"),
  "iron-man":                T("/78lPtwv72eTNqFW9COBYI0dWDJa.jpg"),
  "black-panther":           T("/uxzzxijgPIY7slzFvMotPv8wjKA.jpg"),
  "spider-man-no-way-home":  T("/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg"),
  "thor-ragnarok":           T("/rzRwTcFvttcN1ZpX2xv4j3tSdJu.jpg"),
  "guardians-galaxy":        T("/r7vmZjiyZw9rpJMQJdXpjgiCOk9.jpg"),
  "doctor-strange":          T("/uGBVAWjjA55V6UyhPLHkqbf7Bum.jpg"),
  "the-avengers":            T("/RYMX2wcKCBAr24UyPD7KE3wYQly.jpg"),
  "captain-marvel":          T("/AtsgWhDnHTq68L0lLsUrCnM7TjG.jpg"),
  "spider-man-homecoming":   T("/c24sv2weTHPsmDa7jEMN0m2P3RT.jpg"),
  "captain-america":         T("/vSNxAJTeplixQgzngnFN9CnMmtQ.jpg"),
  "thor":                    T("/prSfAi1xGrhLQNxVSUFh61xAaED.jpg"),
  "ant-man":                 T("/MgEPBFMqPEQ9Bqjm9GQbFXVHAa.jpg"),
  // DC
  "wonder-woman":            T("/imekS7f1OuHyUP2LAiTEM0zBzUz.jpg"),
  "joker":                   T("/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg"),
  "batman-begins":           T("/8RW2runSEc34IwKN2D1aPcJd2UL.jpg"),
  "the-dark-knight-rises":   T("/hr0L2aueqlP2BYUblTTjmtn41Gr.jpg"),
  "aquaman":                 T("/5Kg76ldv7VxeX9YlcQXiowHgdX6.jpg"),
  // Star Wars
  "star-wars-new-hope":      T("/6FfCtAuVAW8XJjZ7eWeLibRLWTw.jpg"),
  "star-wars-empire":        T("/2l05cFWJacyIsTpsqSgH0wQXe4V.jpg"),
  "star-wars-return":        T("/mDCBQNhR6R0PVFucJl1p5okMRpw.jpg"),
  "star-wars-force-awakens": T("/wqnLdwVXoBjKibFRR5U3y0aDUhs.jpg"),
  "rogue-one":               T("/i0yw1mFbB7sNGHCs7EXZPzFkdA1.jpg"),
  // LOTR / HP
  "the-lord-of-the-rings-fellowship": T("/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg"),
  "the-lord-of-the-rings-two-towers": T("/5VTN0pR8gcqV3EPUHHfMGnJYspN.jpg"),
  "the-lord-of-the-rings-return":     T("/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg"),
  "the-hobbit-unexpected-journey":    T("/yHA9Fc37VmpUA5UncTxxo3rTGVA.jpg"),
  "harry-potter-sorcerers-stone":     T("/wuMc08IPKEatf9rnMNXvIDxqP4W.jpg"),
  "harry-potter-chamber":             T("/sdEOH0992YZ0QSxgXNIGLq1ToUi.jpg"),
  "harry-potter-prisoner":            T("/czdhdy59SHgFqKCszkI5klAMQZP.jpg"),
  "harry-potter-goblet":              T("/fECBqgd9q6LSZYO4bnFVFBFJwLz.jpg"),
  "harry-potter-order":               T("/5aOyriQMBg4t7BWJZ9VBRkMTMkl.jpg"),
  "harry-potter-half-blood":          T("/lXS60geme1LlEob5Wce9qCmAGAn.jpg"),
  "harry-potter-deathly-hallows-1":   T("/maP4MTfPCeVD2FZnKEDNCG7Lx0E.jpg"),
  "harry-potter-deathly-hallows-2":   T("/or1gBugydmjToAEq7OZY0owwFk.jpg"),
  // Romance / Drama
  "la-la-land":              T("/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg"),
  "the-notebook":            T("/qom1SZSENdmHFNZBXbtLAGselIZ.jpg"),
  "pride-and-prejudice":     T("/bkfAn9JX3b9cTMCRJUkqiCMFPpB.jpg"),
  "love-actually":           T("/5Kg76ldv7VxeX9YlcQXiowHgdX6.jpg"),
  "crazy-rich-asians":       T("/hr0L2aueqlP2BYUblTTjmtn41Gr.jpg"),
  "to-all-the-boys":         T("/6kBtHFGsGkHDFMtBBBxGPSMPPKJ.jpg"),
  // Comedy
  "mean-girls":              T("/mDCBQNhR6R0PVFucJl1p5okMRpw.jpg"),
  "legally-blonde":          T("/wqnLdwVXoBjKibFRR5U3y0aDUhs.jpg"),
  "the-proposal":            T("/6FfCtAuVAW8XJjZ7eWeLibRLWTw.jpg"),
  // Musical
  "bohemian-rhapsody":       T("/lHu1wtNaczFPGFDTrjCSzeLPTKN.jpg"),
  "the-greatest-showman":    T("/dKha79426AqPKzgOwNnGYSqFfKq.jpg"),
  "mamma-mia":               T("/5Xf0ORxMIXQGTzSjCjxhwLJwHnz.jpg"),
  "grease":                  T("/qom1SZSENdmHFNZBXbtLAGselIZ.jpg"),
  // Hunger Games
  "the-hunger-games":        T("/samTws3MwbQoRNRvWe3OazvaQNJ.jpg"),
  "catching-fire":           T("/umZOGOzTB8bFNBnNnpZXpBQyMjU.jpg"),
  // Asian cinema
  "parasite":                T("/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg"),
  "oldboy":                  T("/pWDtjs568ZfOTMbURQBYuT4Qxka.jpg"),
  "train-to-busan":          T("/oCOFIhCCCRKyAeGnFVCDFKwJVqS.jpg"),
  // Anime series
  "attack-on-titan":         T("/hTP1DtLGFamjfu8WqjnuQdP1n4i.jpg"),
  "death-note":              T("/g3L9ORsHXRIlRnMDGTBOzFbCNkD.jpg"),
  "demon-slayer":            T("/xUfRZu2mi8jH6SzQEJGP6tjBuYj.jpg"),
  "jujutsu-kaisen":          T("/oGyJoUqk5iBqVIBHEGMdBGTbPGH.jpg"),
  "my-hero-academia":        T("/vDHsLnOWKlPGmWs0kGfuhNF4w5l.jpg"),
  "naruto":                  T("/xppeysfvDKVx775MFuH8Z9ex24r.jpg"),
  "one-piece":               T("/e3NBGiAifW9Xt8xD5tpARskjccO.jpg"),
  "fullmetal-alchemist":     T("/lHu1wtNaczFPGFDTrjCSzeLPTKN.jpg"),
  // K-Drama
  "squid-game":              T("/dDlEmu3EZ0Pgg93K2SVNLCjCSvE.jpg"),
  "crash-landing-on-you":    T("/reEMJA1uzscCbkpeRJeTT2bjqUp.jpg"),
  "goblin":                  T("/apbrbWs8M9lyOpJYU5WXrpFbk1Z.jpg"),
  "vincenzo":                T("/nV2cXK5Vrd4vDE0lSS2v3nQRqEV.jpg"),
  "business-proposal":       T("/7PRddO7z7mcPi21nZTCMGShAyy1.jpg"),
  // Western Series
  "breaking-bad":            T("/ggFHVNu6YYI5L9pCfOacjizRGt.jpg"),
  "game-of-thrones":         T("/u3bZgnGQ9T01sWNhyveQz0wH0Hl.jpg"),
  "stranger-things":         T("/49WJfeN0moxb9IPfGn8AIqMGskD.jpg"),
  "the-office":              T("/qWnJzyZhyy74gjpSjIXWmuk0ifX.jpg"),
  "friends":                 T("/f496cm9enuEsZkSPzCwnTESEK5s.jpg"),
  "the-crown":               T("/1M876KPjulVwppEpldhdc8V4o68.jpg"),
  "money-heist":             T("/reEMJA1uzscCbkpeRJeTT2bjqUp.jpg"),
  "dark":                    T("/apbrbWs8M9lyOpJYU5WXrpFbk1Z.jpg"),
  "black-mirror":            T("/7PRddO7z7mcPi21nZTCMGShAyy1.jpg"),
  "the-witcher":             T("/cZ0d3rtvXPVvuiX22sP79K3Hmjz.jpg"),
  "wednesday":               T("/9PFonBhy4cQy7Jz20NpMygczOkv.jpg"),
  "emily-in-paris":          T("/1tnkFBGfFJMDFqpr7SwNHFMnNQe.jpg"),
  "bridgerton":              T("/luoKpgVwi1E5nQsi7W0UuKHu2Rq.jpg"),
  "the-queens-gambit":       T("/zU0htwkhNvBQdVSIKB9s6hgVeFK.jpg"),
  "ted-lasso":               T("/5fhZdwP1DVJ0FyVH6vrFdHwpXIn.jpg"),
  "succession":              T("/e2X8xMNuLtSQBEFALLCRHpRGHRB.jpg"),
  "euphoria":                T("/jtnfNzqZwN4E32FGGxx1YZaBWWf.jpg"),
  "sex-education":           T("/lYqC8Amj4owX05xQg5Yo7uUHgah.jpg"),
  "the-mandalorian":         T("/sWgBv7LV2reenceBXyaIZVLuiEG.jpg"),
  "loki":                    T("/kEl2t3OhXc3Zb9FBh1AuYzRTgZp.jpg"),
  "wandavision":             T("/glKDfE6btIRcmuj5lp2E4FFWqOB.jpg"),
  "the-boys":                T("/stTEycfG9928HYGEISBFaG1ngjM.jpg"),
  "invincible":              T("/yDWJYRAwMNKa951FiQGa9mlQkwt.jpg"),
  "arcane":                  T("/fqldf2t8ztc9aiwn3k6mlX3tvRT.jpg"),
  "mindhunter":              T("/nV2cXK5Vrd4vDE0lSS2v3nQRqEV.jpg"),
};

export const GENRES = [
  'Fairytale', 'Musical', 'Romance', 'Adventure', 'Comedy',
  'Drama', 'Action', 'Family', 'Fantasy', 'Sci-Fi', 'War', 'Historical', 'Horror'
];

export const TYPES = [
  { id: 'movie', label: 'Movies', emoji: '🎬' },
  { id: 'animation', label: 'Animation', emoji: '🎈' },
  { id: 'series', label: 'Series', emoji: '📺' },
  { id: 'dorama', label: 'K-Drama', emoji: '🌸' },
  { id: 'anime', label: 'Anime', emoji: '⛩️' },
];

export function getPoster(id: string): string | undefined {
  return POSTER_MAP[id];
}

export function formatRuntime(minutes: number): string {
  if (minutes < 60) return `${minutes}m`;
  const h = Math.floor(minutes / 60);
  const m = minutes % 60;
  if (m === 0) return `${h}h`;
  return `${h}h ${m}m`;
}

export const MOVIES: Movie[] = [
  // Disney Animation
  { id: 'cinderella', title: 'Cinderella', year: 1950, runtime: 74, emoji: '👠', kind: 'animation', tags: ['disney', 'princess', 'classic', 'fairytale', 'musical', 'romance'] },
  { id: 'snow-white', title: 'Snow White', year: 1937, runtime: 83, emoji: '🍎', kind: 'animation', tags: ['disney', 'princess', 'classic', 'fairytale', 'musical'] },
  { id: 'little-mermaid', title: 'The Little Mermaid', year: 1989, runtime: 83, emoji: '🧜', kind: 'animation', tags: ['disney', 'princess', 'fairytale', 'musical', 'romance'] },
  { id: 'beauty-beast', title: 'Beauty and the Beast', year: 1991, runtime: 84, emoji: '🌹', kind: 'animation', tags: ['disney', 'princess', 'fairytale', 'musical', 'romance'] },
  { id: 'aladdin', title: 'Aladdin', year: 1992, runtime: 90, emoji: '🪔', kind: 'animation', tags: ['disney', 'musical', 'fairytale', 'adventure'] },
  { id: 'lion-king', title: 'The Lion King', year: 1994, runtime: 88, emoji: '🦁', kind: 'animation', tags: ['disney', 'musical', 'adventure', 'family'] },
  { id: 'mulan', title: 'Mulan', year: 1998, runtime: 88, emoji: '🐉', kind: 'animation', tags: ['disney', 'princess', 'adventure', 'musical'] },
  { id: 'pocahontas', title: 'Pocahontas', year: 1995, runtime: 81, emoji: '🍃', kind: 'animation', tags: ['disney', 'princess', 'musical', 'romance'] },
  { id: 'tangled', title: 'Tangled', year: 2010, runtime: 100, emoji: '🌟', kind: 'animation', tags: ['disney', 'princess', 'fairytale', 'musical', 'romance'] },
  { id: 'frozen', title: 'Frozen', year: 2013, runtime: 102, emoji: '❄️', kind: 'animation', tags: ['disney', 'princess', 'musical', 'family'] },
  { id: 'moana', title: 'Moana', year: 2016, runtime: 107, emoji: '🌊', kind: 'animation', tags: ['disney', 'princess', 'musical', 'adventure'] },
  { id: 'encanto', title: 'Encanto', year: 2021, runtime: 102, emoji: '🦋', kind: 'animation', tags: ['disney', 'family', 'musical'] },
  { id: 'raya', title: 'Raya and the Last Dragon', year: 2021, runtime: 107, emoji: '🐉', kind: 'animation', tags: ['disney', 'adventure', 'fantasy', 'family'] },
  { id: 'wish', title: 'Wish', year: 2023, runtime: 95, emoji: '⭐', kind: 'animation', tags: ['disney', 'musical', 'fantasy', 'family'] },
  // Pixar
  { id: 'toy-story', title: 'Toy Story', year: 1995, runtime: 81, emoji: '🤠', kind: 'animation', tags: ['pixar', 'family', 'adventure', 'comedy'] },
  { id: 'finding-nemo', title: 'Finding Nemo', year: 2003, runtime: 100, emoji: '🐠', kind: 'animation', tags: ['pixar', 'family', 'adventure'] },
  { id: 'up', title: 'Up', year: 2009, runtime: 96, emoji: '🎈', kind: 'animation', tags: ['pixar', 'family', 'adventure', 'drama'] },
  { id: 'wall-e', title: 'WALL·E', year: 2008, runtime: 98, emoji: '🤖', kind: 'animation', tags: ['pixar', 'family', 'romance'] },
  { id: 'ratatouille', title: 'Ratatouille', year: 2007, runtime: 111, emoji: '🐭', kind: 'animation', tags: ['pixar', 'family', 'comedy'] },
  { id: 'inside-out', title: 'Inside Out', year: 2015, runtime: 95, emoji: '🧠', kind: 'animation', tags: ['pixar', 'family', 'drama'] },
  { id: 'coco', title: 'Coco', year: 2017, runtime: 105, emoji: '🎸', kind: 'animation', tags: ['pixar', 'family', 'musical', 'drama'] },
  { id: 'soul', title: 'Soul', year: 2020, runtime: 100, emoji: '🎹', kind: 'animation', tags: ['pixar', 'family', 'drama'] },
  { id: 'luca', title: 'Luca', year: 2021, runtime: 95, emoji: '🦎', kind: 'animation', tags: ['pixar', 'family', 'adventure', 'comedy'] },
  { id: 'turning-red', title: 'Turning Red', year: 2022, runtime: 100, emoji: '🐼', kind: 'animation', tags: ['pixar', 'family', 'comedy'] },
  { id: 'elemental', title: 'Elemental', year: 2023, runtime: 101, emoji: '🔥', kind: 'animation', tags: ['pixar', 'family', 'romance'] },
  { id: 'the-incredibles', title: 'The Incredibles', year: 2004, runtime: 115, emoji: '🦸', kind: 'animation', tags: ['pixar', 'family', 'action', 'adventure'] },
  { id: 'brave', title: 'Brave', year: 2012, runtime: 93, emoji: '🏹', kind: 'animation', tags: ['pixar', 'princess', 'adventure', 'family'] },
  { id: 'monsters-inc', title: "Monsters, Inc.", year: 2001, runtime: 92, emoji: '👾', kind: 'animation', tags: ['pixar', 'family', 'comedy', 'adventure'] },
  { id: 'cars', title: 'Cars', year: 2006, runtime: 117, emoji: '🚗', kind: 'animation', tags: ['pixar', 'family', 'adventure', 'comedy'] },
  // Ghibli
  { id: 'spirited-away', title: 'Spirited Away', year: 2001, runtime: 125, emoji: '🐉', kind: 'animation', tags: ['ghibli', 'anime', 'fairytale', 'adventure'] },
  { id: 'totoro', title: 'My Neighbor Totoro', year: 1988, runtime: 86, emoji: '🌳', kind: 'animation', tags: ['ghibli', 'anime', 'family', 'fantasy'] },
  { id: 'howls-moving-castle', title: "Howl's Moving Castle", year: 2004, runtime: 119, emoji: '🏰', kind: 'animation', tags: ['ghibli', 'anime', 'fantasy', 'romance', 'adventure'] },
  { id: 'princess-mononoke', title: 'Princess Mononoke', year: 1997, runtime: 134, emoji: '🐺', kind: 'animation', tags: ['ghibli', 'anime', 'adventure', 'fantasy', 'drama'] },
  { id: 'kiki', title: "Kiki's Delivery Service", year: 1989, runtime: 103, emoji: '🧹', kind: 'animation', tags: ['ghibli', 'anime', 'fairytale', 'adventure'] },
  { id: 'nausicaa', title: 'Nausicaä of the Valley of the Wind', year: 1984, runtime: 117, emoji: '🌬️', kind: 'animation', tags: ['ghibli', 'anime', 'adventure', 'fantasy'] },
  { id: 'castle-sky', title: 'Castle in the Sky', year: 1986, runtime: 124, emoji: '🏯', kind: 'animation', tags: ['ghibli', 'anime', 'adventure', 'fantasy'] },
  { id: 'ponyo', title: 'Ponyo', year: 2008, runtime: 101, emoji: '🐟', kind: 'animation', tags: ['ghibli', 'anime', 'fairytale', 'family'] },
  { id: 'grave-fireflies', title: 'Grave of the Fireflies', year: 1988, runtime: 89, emoji: '🌟', kind: 'animation', tags: ['ghibli', 'anime', 'drama', 'war', 'historical'] },
  // Other animation
  { id: 'shrek', title: 'Shrek', year: 2001, runtime: 90, emoji: '🟢', kind: 'animation', tags: ['comedy', 'fairytale', 'adventure', 'romance'] },
  { id: 'shrek-2', title: 'Shrek 2', year: 2004, runtime: 93, emoji: '🟢', kind: 'animation', tags: ['comedy', 'fairytale', 'adventure', 'romance'] },
  { id: 'kung-fu-panda', title: 'Kung Fu Panda', year: 2008, runtime: 92, emoji: '🐼', kind: 'animation', tags: ['comedy', 'adventure', 'action', 'family'] },
  { id: 'how-to-train-your-dragon', title: 'How to Train Your Dragon', year: 2010, runtime: 98, emoji: '🐲', kind: 'animation', tags: ['adventure', 'fantasy', 'family'] },
  { id: 'despicable-me', title: 'Despicable Me', year: 2010, runtime: 95, emoji: '💛', kind: 'animation', tags: ['comedy', 'family', 'adventure'] },
  { id: 'zootopia', title: 'Zootopia', year: 2016, runtime: 108, emoji: '🦊', kind: 'animation', tags: ['adventure', 'comedy', 'family', 'drama'] },
  { id: 'wreck-it-ralph', title: 'Wreck-It Ralph', year: 2012, runtime: 101, emoji: '🕹️', kind: 'animation', tags: ['adventure', 'comedy', 'family'] },
  { id: 'big-hero-6', title: 'Big Hero 6', year: 2014, runtime: 102, emoji: '🤖', kind: 'animation', tags: ['adventure', 'action', 'family'] },
  // Movies
  { id: 'avatar', title: 'Avatar', year: 2009, runtime: 162, emoji: '🌿', kind: 'movie', tags: ['sci-fi', 'adventure', 'action', 'fantasy'] },
  { id: 'titanic', title: 'Titanic', year: 1997, runtime: 194, emoji: '🚢', kind: 'movie', tags: ['romance', 'drama', 'historical'] },
  { id: 'inception', title: 'Inception', year: 2010, runtime: 148, emoji: '🌀', kind: 'movie', tags: ['sci-fi', 'action', 'adventure', 'drama'] },
  { id: 'interstellar', title: 'Interstellar', year: 2014, runtime: 169, emoji: '🌌', kind: 'movie', tags: ['sci-fi', 'adventure', 'drama'] },
  { id: 'the-dark-knight', title: 'The Dark Knight', year: 2008, runtime: 152, emoji: '🦇', kind: 'movie', tags: ['action', 'drama'] },
  { id: 'forrest-gump', title: 'Forrest Gump', year: 1994, runtime: 142, emoji: '🏃', kind: 'movie', tags: ['drama', 'romance', 'comedy', 'historical'] },
  { id: 'the-shawshank-redemption', title: 'The Shawshank Redemption', year: 1994, runtime: 142, emoji: '🔓', kind: 'movie', tags: ['drama'] },
  { id: 'schindlers-list', title: "Schindler's List", year: 1993, runtime: 195, emoji: '📋', kind: 'movie', tags: ['drama', 'historical', 'war'] },
  { id: 'the-godfather', title: 'The Godfather', year: 1972, runtime: 175, emoji: '🌹', kind: 'movie', tags: ['drama', 'action'] },
  { id: 'pulp-fiction', title: 'Pulp Fiction', year: 1994, runtime: 154, emoji: '💼', kind: 'movie', tags: ['action', 'drama', 'comedy'] },
  { id: 'the-matrix', title: 'The Matrix', year: 1999, runtime: 136, emoji: '💊', kind: 'movie', tags: ['sci-fi', 'action', 'adventure'] },
  { id: 'gladiator', title: 'Gladiator', year: 2000, runtime: 155, emoji: '⚔️', kind: 'movie', tags: ['action', 'drama', 'historical', 'adventure'] },
  { id: 'fight-club', title: 'Fight Club', year: 1999, runtime: 139, emoji: '👊', kind: 'movie', tags: ['drama', 'action'] },
  { id: 'goodfellas', title: 'Goodfellas', year: 1990, runtime: 146, emoji: '🔫', kind: 'movie', tags: ['drama', 'action'] },
  { id: 'jurassic-park', title: 'Jurassic Park', year: 1993, runtime: 127, emoji: '🦕', kind: 'movie', tags: ['sci-fi', 'adventure', 'action'] },
  { id: 'home-alone', title: 'Home Alone', year: 1990, runtime: 103, emoji: '🏠', kind: 'movie', tags: ['comedy', 'family', 'adventure'] },
  { id: 'the-lion-king-2019', title: 'The Lion King (2019)', year: 2019, runtime: 118, emoji: '🦁', kind: 'movie', tags: ['adventure', 'family', 'musical'] },
  // Marvel
  { id: 'avengers-endgame', title: 'Avengers: Endgame', year: 2019, runtime: 181, emoji: '🦸', kind: 'movie', tags: ['action', 'adventure', 'sci-fi', 'fantasy'] },
  { id: 'avengers-infinity-war', title: 'Avengers: Infinity War', year: 2018, runtime: 149, emoji: '🌌', kind: 'movie', tags: ['action', 'adventure', 'sci-fi', 'fantasy'] },
  { id: 'iron-man', title: 'Iron Man', year: 2008, runtime: 126, emoji: '🤖', kind: 'movie', tags: ['action', 'adventure', 'sci-fi'] },
  { id: 'black-panther', title: 'Black Panther', year: 2018, runtime: 134, emoji: '🐆', kind: 'movie', tags: ['action', 'adventure', 'sci-fi', 'fantasy'] },
  { id: 'spider-man-no-way-home', title: 'Spider-Man: No Way Home', year: 2021, runtime: 148, emoji: '🕷️', kind: 'movie', tags: ['action', 'adventure', 'sci-fi', 'fantasy'] },
  { id: 'thor-ragnarok', title: 'Thor: Ragnarok', year: 2017, runtime: 130, emoji: '⚡', kind: 'movie', tags: ['action', 'adventure', 'comedy', 'fantasy'] },
  { id: 'guardians-galaxy', title: 'Guardians of the Galaxy', year: 2014, runtime: 121, emoji: '🚀', kind: 'movie', tags: ['action', 'adventure', 'comedy', 'sci-fi'] },
  { id: 'doctor-strange', title: 'Doctor Strange', year: 2016, runtime: 115, emoji: '🔮', kind: 'movie', tags: ['action', 'adventure', 'fantasy', 'sci-fi'] },
  { id: 'the-avengers', title: 'The Avengers', year: 2012, runtime: 143, emoji: '⚡', kind: 'movie', tags: ['action', 'adventure', 'sci-fi', 'fantasy'] },
  { id: 'captain-marvel', title: 'Captain Marvel', year: 2019, runtime: 124, emoji: '⭐', kind: 'movie', tags: ['action', 'adventure', 'sci-fi'] },
  { id: 'spider-man-homecoming', title: 'Spider-Man: Homecoming', year: 2017, runtime: 133, emoji: '🕷️', kind: 'movie', tags: ['action', 'adventure', 'comedy'] },
  { id: 'captain-america', title: 'Captain America', year: 2011, runtime: 124, emoji: '🛡️', kind: 'movie', tags: ['action', 'adventure', 'war'] },
  { id: 'thor', title: 'Thor', year: 2011, runtime: 115, emoji: '⚡', kind: 'movie', tags: ['action', 'adventure', 'fantasy'] },
  { id: 'ant-man', title: 'Ant-Man', year: 2015, runtime: 117, emoji: '🐜', kind: 'movie', tags: ['action', 'adventure', 'comedy', 'sci-fi'] },
  // DC
  { id: 'wonder-woman', title: 'Wonder Woman', year: 2017, runtime: 141, emoji: '⚔️', kind: 'movie', tags: ['action', 'adventure', 'fantasy', 'war'] },
  { id: 'joker', title: 'Joker', year: 2019, runtime: 122, emoji: '🃏', kind: 'movie', tags: ['drama', 'action'] },
  { id: 'batman-begins', title: 'Batman Begins', year: 2005, runtime: 140, emoji: '🦇', kind: 'movie', tags: ['action', 'adventure', 'drama'] },
  { id: 'the-dark-knight-rises', title: 'The Dark Knight Rises', year: 2012, runtime: 164, emoji: '🦇', kind: 'movie', tags: ['action', 'adventure', 'drama'] },
  { id: 'aquaman', title: 'Aquaman', year: 2018, runtime: 143, emoji: '🌊', kind: 'movie', tags: ['action', 'adventure', 'fantasy'] },
  // Star Wars
  { id: 'star-wars-new-hope', title: 'Star Wars: A New Hope', year: 1977, runtime: 121, emoji: '⭐', kind: 'movie', tags: ['sci-fi', 'adventure', 'action', 'fantasy'] },
  { id: 'star-wars-empire', title: 'The Empire Strikes Back', year: 1980, runtime: 124, emoji: '🌑', kind: 'movie', tags: ['sci-fi', 'adventure', 'action', 'fantasy'] },
  { id: 'star-wars-return', title: 'Return of the Jedi', year: 1983, runtime: 131, emoji: '🌟', kind: 'movie', tags: ['sci-fi', 'adventure', 'action', 'fantasy'] },
  { id: 'star-wars-force-awakens', title: 'The Force Awakens', year: 2015, runtime: 138, emoji: '⚡', kind: 'movie', tags: ['sci-fi', 'adventure', 'action', 'fantasy'] },
  { id: 'rogue-one', title: 'Rogue One', year: 2016, runtime: 133, emoji: '🔫', kind: 'movie', tags: ['sci-fi', 'adventure', 'action', 'war'] },
  // LOTR / HP
  { id: 'the-lord-of-the-rings-fellowship', title: 'The Fellowship of the Ring', year: 2001, runtime: 178, emoji: '💍', kind: 'movie', tags: ['adventure', 'fantasy', 'drama', 'action'] },
  { id: 'the-lord-of-the-rings-two-towers', title: 'The Two Towers', year: 2002, runtime: 179, emoji: '🗼', kind: 'movie', tags: ['adventure', 'fantasy', 'drama', 'action', 'war'] },
  { id: 'the-lord-of-the-rings-return', title: 'The Return of the King', year: 2003, runtime: 201, emoji: '👑', kind: 'movie', tags: ['adventure', 'fantasy', 'drama', 'action', 'war'] },
  { id: 'the-hobbit-unexpected-journey', title: 'The Hobbit: An Unexpected Journey', year: 2012, runtime: 169, emoji: '🧙', kind: 'movie', tags: ['adventure', 'fantasy', 'drama'] },
  { id: 'harry-potter-sorcerers-stone', title: "Harry Potter and the Sorcerer's Stone", year: 2001, runtime: 152, emoji: '🧙', kind: 'movie', tags: ['fantasy', 'adventure', 'family'] },
  { id: 'harry-potter-chamber', title: 'Harry Potter and the Chamber of Secrets', year: 2002, runtime: 161, emoji: '🐍', kind: 'movie', tags: ['fantasy', 'adventure', 'family'] },
  { id: 'harry-potter-prisoner', title: 'Harry Potter and the Prisoner of Azkaban', year: 2004, runtime: 142, emoji: '🐺', kind: 'movie', tags: ['fantasy', 'adventure', 'family'] },
  { id: 'harry-potter-goblet', title: 'Harry Potter and the Goblet of Fire', year: 2005, runtime: 157, emoji: '🔥', kind: 'movie', tags: ['fantasy', 'adventure', 'family'] },
  { id: 'harry-potter-order', title: 'Harry Potter and the Order of the Phoenix', year: 2007, runtime: 138, emoji: '🦅', kind: 'movie', tags: ['fantasy', 'adventure', 'family'] },
  { id: 'harry-potter-half-blood', title: 'Harry Potter and the Half-Blood Prince', year: 2009, runtime: 153, emoji: '📖', kind: 'movie', tags: ['fantasy', 'adventure', 'family'] },
  { id: 'harry-potter-deathly-hallows-1', title: 'Deathly Hallows Part 1', year: 2010, runtime: 146, emoji: '⚡', kind: 'movie', tags: ['fantasy', 'adventure', 'drama'] },
  { id: 'harry-potter-deathly-hallows-2', title: 'Deathly Hallows Part 2', year: 2011, runtime: 130, emoji: '⚡', kind: 'movie', tags: ['fantasy', 'adventure', 'drama', 'action'] },
  // Romance / Drama
  { id: 'la-la-land', title: 'La La Land', year: 2016, runtime: 128, emoji: '🌆', kind: 'movie', tags: ['romance', 'musical', 'drama'] },
  { id: 'the-notebook', title: 'The Notebook', year: 2004, runtime: 123, emoji: '📓', kind: 'movie', tags: ['romance', 'drama'] },
  { id: 'pride-and-prejudice', title: 'Pride & Prejudice', year: 2005, runtime: 129, emoji: '🌹', kind: 'movie', tags: ['romance', 'drama', 'historical'] },
  { id: 'love-actually', title: 'Love Actually', year: 2003, runtime: 135, emoji: '❤️', kind: 'movie', tags: ['romance', 'comedy', 'drama'] },
  { id: 'crazy-rich-asians', title: 'Crazy Rich Asians', year: 2018, runtime: 120, emoji: '💎', kind: 'movie', tags: ['romance', 'comedy', 'drama'] },
  { id: 'to-all-the-boys', title: "To All the Boys I've Loved Before", year: 2018, runtime: 99, emoji: '💌', kind: 'movie', tags: ['romance', 'comedy'] },
  // Comedy
  { id: 'mean-girls', title: 'Mean Girls', year: 2004, runtime: 97, emoji: '💅', kind: 'movie', tags: ['comedy', 'drama'] },
  { id: 'legally-blonde', title: 'Legally Blonde', year: 2001, runtime: 96, emoji: '👱', kind: 'movie', tags: ['comedy', 'romance', 'drama'] },
  { id: 'the-proposal', title: 'The Proposal', year: 2009, runtime: 108, emoji: '💍', kind: 'movie', tags: ['comedy', 'romance'] },
  // Musical
  { id: 'bohemian-rhapsody', title: 'Bohemian Rhapsody', year: 2018, runtime: 134, emoji: '🎸', kind: 'movie', tags: ['drama', 'musical', 'historical'] },
  { id: 'the-greatest-showman', title: 'The Greatest Showman', year: 2017, runtime: 105, emoji: '🎪', kind: 'movie', tags: ['musical', 'drama', 'historical'] },
  { id: 'mamma-mia', title: 'Mamma Mia!', year: 2008, runtime: 108, emoji: '🎵', kind: 'movie', tags: ['musical', 'romance', 'comedy'] },
  { id: 'grease', title: 'Grease', year: 1978, runtime: 110, emoji: '🎶', kind: 'movie', tags: ['musical', 'romance', 'comedy'] },
  // Hunger Games
  { id: 'the-hunger-games', title: 'The Hunger Games', year: 2012, runtime: 142, emoji: '🏹', kind: 'movie', tags: ['action', 'adventure', 'sci-fi', 'drama'] },
  { id: 'catching-fire', title: 'Catching Fire', year: 2013, runtime: 146, emoji: '🔥', kind: 'movie', tags: ['action', 'adventure', 'sci-fi', 'drama'] },
  // Asian cinema
  { id: 'parasite', title: 'Parasite', year: 2019, runtime: 132, emoji: '🏠', kind: 'movie', tags: ['drama', 'comedy', 'horror'] },
  { id: 'oldboy', title: 'Oldboy', year: 2003, runtime: 120, emoji: '🔨', kind: 'movie', tags: ['drama', 'action', 'horror'] },
  { id: 'train-to-busan', title: 'Train to Busan', year: 2016, runtime: 118, emoji: '🚂', kind: 'movie', tags: ['horror', 'action', 'drama'] },
  // Anime movies
  { id: 'your-name', title: 'Your Name', year: 2016, runtime: 106, emoji: '🌠', kind: 'anime', tags: ['romance', 'fantasy', 'drama'] },
  { id: 'weathering-with-you', title: 'Weathering with You', year: 2019, runtime: 112, emoji: '☀️', kind: 'anime', tags: ['romance', 'fantasy', 'drama'] },
  { id: 'suzume', title: 'Suzume', year: 2022, runtime: 122, emoji: '🚪', kind: 'anime', tags: ['adventure', 'fantasy', 'romance', 'drama'] },
  { id: 'a-silent-voice', title: 'A Silent Voice', year: 2016, runtime: 130, emoji: '🤫', kind: 'anime', tags: ['drama', 'romance'] },
  // Anime series
  { id: 'attack-on-titan', title: 'Attack on Titan', year: 2013, runtime: 1440, emoji: '⚔️', kind: 'anime', tags: ['action', 'drama', 'fantasy', 'horror', 'war'] },
  { id: 'death-note', title: 'Death Note', year: 2006, runtime: 600, emoji: '📓', kind: 'anime', tags: ['drama', 'fantasy', 'horror'] },
  { id: 'fullmetal-alchemist', title: 'Fullmetal Alchemist: Brotherhood', year: 2009, runtime: 1500, emoji: '⚗️', kind: 'anime', tags: ['adventure', 'action', 'drama', 'fantasy'] },
  { id: 'naruto', title: 'Naruto', year: 2002, runtime: 5400, emoji: '🍥', kind: 'anime', tags: ['action', 'adventure', 'comedy', 'drama'] },
  { id: 'one-piece', title: 'One Piece', year: 1999, runtime: 18000, emoji: '🏴‍☠️', kind: 'anime', tags: ['action', 'adventure', 'comedy', 'fantasy'] },
  { id: 'demon-slayer', title: 'Demon Slayer', year: 2019, runtime: 720, emoji: '🗡️', kind: 'anime', tags: ['action', 'adventure', 'fantasy', 'drama'] },
  { id: 'jujutsu-kaisen', title: 'Jujutsu Kaisen', year: 2020, runtime: 600, emoji: '👁️', kind: 'anime', tags: ['action', 'adventure', 'fantasy', 'horror'] },
  { id: 'my-hero-academia', title: 'My Hero Academia', year: 2016, runtime: 2400, emoji: '🦸', kind: 'anime', tags: ['action', 'adventure', 'comedy', 'drama'] },
  // K-Drama
  { id: 'crash-landing-on-you', title: 'Crash Landing on You', year: 2019, runtime: 1080, emoji: '🪂', kind: 'dorama', tags: ['romance', 'drama', 'comedy'] },
  { id: 'goblin', title: 'Goblin', year: 2016, runtime: 960, emoji: '👺', kind: 'dorama', tags: ['romance', 'drama', 'fantasy'] },
  { id: 'vincenzo', title: 'Vincenzo', year: 2021, runtime: 1320, emoji: '🤵', kind: 'dorama', tags: ['action', 'drama', 'comedy', 'romance'] },
  { id: 'business-proposal', title: 'A Business Proposal', year: 2022, runtime: 720, emoji: '💼', kind: 'dorama', tags: ['romance', 'comedy', 'drama'] },
  { id: 'squid-game', title: 'Squid Game', year: 2021, runtime: 540, emoji: '🦑', kind: 'dorama', tags: ['drama', 'action', 'horror'] },
  // Western Series
  { id: 'breaking-bad', title: 'Breaking Bad', year: 2008, runtime: 2970, emoji: '⚗️', kind: 'series', tags: ['drama', 'action'] },
  { id: 'game-of-thrones', title: 'Game of Thrones', year: 2011, runtime: 4380, emoji: '👑', kind: 'series', tags: ['drama', 'action', 'fantasy', 'war'] },
  { id: 'stranger-things', title: 'Stranger Things', year: 2016, runtime: 2160, emoji: '🔦', kind: 'series', tags: ['sci-fi', 'horror', 'drama', 'adventure'] },
  { id: 'the-office', title: 'The Office', year: 2005, runtime: 3600, emoji: '💼', kind: 'series', tags: ['comedy', 'drama', 'romance'] },
  { id: 'friends', title: 'Friends', year: 1994, runtime: 5040, emoji: '☕', kind: 'series', tags: ['comedy', 'romance', 'drama'] },
  { id: 'the-crown', title: 'The Crown', year: 2016, runtime: 3000, emoji: '👑', kind: 'series', tags: ['drama', 'historical', 'romance'] },
  { id: 'money-heist', title: 'Money Heist', year: 2017, runtime: 2400, emoji: '💰', kind: 'series', tags: ['action', 'drama', 'romance'] },
  { id: 'dark', title: 'Dark', year: 2017, runtime: 1620, emoji: '🌑', kind: 'series', tags: ['sci-fi', 'drama', 'horror'] },
  { id: 'black-mirror', title: 'Black Mirror', year: 2011, runtime: 1800, emoji: '📱', kind: 'series', tags: ['sci-fi', 'drama', 'horror'] },
  { id: 'the-witcher', title: 'The Witcher', year: 2019, runtime: 1440, emoji: '⚔️', kind: 'series', tags: ['action', 'adventure', 'fantasy', 'drama'] },
  { id: 'wednesday', title: 'Wednesday', year: 2022, runtime: 480, emoji: '🖤', kind: 'series', tags: ['horror', 'comedy', 'fantasy'] },
  { id: 'emily-in-paris', title: 'Emily in Paris', year: 2020, runtime: 960, emoji: '🗼', kind: 'series', tags: ['comedy', 'romance', 'drama'] },
  { id: 'bridgerton', title: 'Bridgerton', year: 2020, runtime: 960, emoji: '🌸', kind: 'series', tags: ['romance', 'drama', 'historical'] },
  { id: 'the-queens-gambit', title: "The Queen's Gambit", year: 2020, runtime: 420, emoji: '♟️', kind: 'series', tags: ['drama', 'historical'] },
  { id: 'ted-lasso', title: 'Ted Lasso', year: 2020, runtime: 1440, emoji: '⚽', kind: 'series', tags: ['comedy', 'drama', 'romance'] },
  { id: 'succession', title: 'Succession', year: 2018, runtime: 2400, emoji: '💰', kind: 'series', tags: ['drama', 'comedy'] },
  { id: 'euphoria', title: 'Euphoria', year: 2019, runtime: 960, emoji: '✨', kind: 'series', tags: ['drama'] },
  { id: 'sex-education', title: 'Sex Education', year: 2019, runtime: 1440, emoji: '📚', kind: 'series', tags: ['comedy', 'drama', 'romance'] },
  { id: 'the-mandalorian', title: 'The Mandalorian', year: 2019, runtime: 960, emoji: '🪖', kind: 'series', tags: ['action', 'adventure', 'sci-fi', 'fantasy'] },
  { id: 'loki', title: 'Loki', year: 2021, runtime: 360, emoji: '🐍', kind: 'series', tags: ['action', 'adventure', 'sci-fi', 'fantasy'] },
  { id: 'wandavision', title: 'WandaVision', year: 2021, runtime: 360, emoji: '🔮', kind: 'series', tags: ['action', 'drama', 'sci-fi', 'fantasy'] },
  { id: 'the-boys', title: 'The Boys', year: 2019, runtime: 1440, emoji: '💥', kind: 'series', tags: ['action', 'drama', 'comedy', 'sci-fi'] },
  { id: 'invincible', title: 'Invincible', year: 2021, runtime: 480, emoji: '🦸', kind: 'series', tags: ['action', 'adventure', 'drama', 'sci-fi'] },
  { id: 'arcane', title: 'Arcane', year: 2021, runtime: 540, emoji: '⚡', kind: 'series', tags: ['action', 'adventure', 'fantasy', 'drama'] },
  { id: 'mindhunter', title: 'Mindhunter', year: 2017, runtime: 1200, emoji: '🔍', kind: 'series', tags: ['drama', 'horror'] },
];
